/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as PricingRouteRouteImport } from './routes/pricing/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthSignUpRouteRouteImport } from './routes/auth/sign-up/route'
import { Route as AuthSignInRouteRouteImport } from './routes/auth/sign-in/route'
import { Route as ApiChatRouteRouteImport } from './routes/api/chat/route'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutIndexRouteImport } from './routes/(app)/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appLayoutSplatRouteImport } from './routes/(app)/_layout/$'
import { Route as AuthAcceptInvitationIdRouteRouteImport } from './routes/auth/accept-invitation/$id/route'
import { Route as ApiZeroQueryRouteRouteImport } from './routes/api/zero/query/route'
import { Route as ApiZeroMutateRouteRouteImport } from './routes/api/zero/mutate/route'
import { Route as ApiOrgModelPolicyRouteRouteImport } from './routes/api/org/model-policy/route'
import { Route as ApiFilesUploadRouteRouteImport } from './routes/api/files/upload/route'
import { Route as ApiFilesMarkdownRouteRouteImport } from './routes/api/files/markdown/route'
import { Route as eeSingularityLayoutRouteRouteImport } from './routes/(ee)/singularity/_layout/route'
import { Route as appLayoutSettingsRouteRouteImport } from './routes/(app)/_layout/settings/route'
import { Route as appLayoutOrganizationRouteRouteImport } from './routes/(app)/_layout/organization/route'
import { Route as appLayoutChatRouteRouteImport } from './routes/(app)/_layout/chat/route'
import { Route as eeSingularityLayoutIndexRouteImport } from './routes/(ee)/singularity/_layout/index'
import { Route as appLayoutSettingsIndexRouteImport } from './routes/(app)/_layout/settings/index'
import { Route as appLayoutChatIndexRouteImport } from './routes/(app)/_layout/chat/index'
import { Route as appLayoutSettingsSecurityRouteRouteImport } from './routes/(app)/_layout/settings/security/route'
import { Route as appLayoutOrganizationSettingsRouteRouteImport } from './routes/(app)/_layout/organization/settings/route'
import { Route as appLayoutChatThreadIdRouteRouteImport } from './routes/(app)/_layout/chat/$threadId/route'
import { Route as appLayoutOrganizationSettingsIndexRouteImport } from './routes/(app)/_layout/organization/settings/index'
import { Route as eeSingularityLayoutOrgsOrganizationIdRouteImport } from './routes/(ee)/singularity/_layout/orgs/$organizationId'
import { Route as appLayoutOrganizationSettingsToolsRouteRouteImport } from './routes/(app)/_layout/organization/settings/tools/route'
import { Route as appLayoutOrganizationSettingsSecurityRouteRouteImport } from './routes/(app)/_layout/organization/settings/security/route'
import { Route as appLayoutOrganizationSettingsProviderPolicyRouteRouteImport } from './routes/(app)/_layout/organization/settings/provider-policy/route'
import { Route as appLayoutOrganizationSettingsModelsRouteRouteImport } from './routes/(app)/_layout/organization/settings/models/route'
import { Route as appLayoutOrganizationSettingsMembersRouteRouteImport } from './routes/(app)/_layout/organization/settings/members/route'
import { Route as appLayoutOrganizationSettingsKnowledgeRouteRouteImport } from './routes/(app)/_layout/organization/settings/knowledge/route'
import { Route as appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport } from './routes/(app)/_layout/organization/settings/compliance-policy/route'
import { Route as appLayoutOrganizationSettingsByokRouteRouteImport } from './routes/(app)/_layout/organization/settings/byok/route'
import { Route as appLayoutOrganizationSettingsBillingRouteRouteImport } from './routes/(app)/_layout/organization/settings/billing/route'
import { Route as appLayoutOrganizationSettingsAnalyticsRouteRouteImport } from './routes/(app)/_layout/organization/settings/analytics/route'
import { Route as appLayoutOrganizationSettingsModelsIndexRouteImport } from './routes/(app)/_layout/organization/settings/models/index'
import { Route as appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport } from './routes/(app)/_layout/organization/settings/models/$providerId/route'

const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRouteRoute = PricingRouteRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRouteRoute = AuthSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRouteRoute = AuthSignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiChatRouteRoute = ApiChatRouteRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutIndexRoute = appLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutSplatRoute = appLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const AuthAcceptInvitationIdRouteRoute =
  AuthAcceptInvitationIdRouteRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const ApiZeroQueryRouteRoute = ApiZeroQueryRouteRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRouteRoute = ApiZeroMutateRouteRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgModelPolicyRouteRoute = ApiOrgModelPolicyRouteRouteImport.update({
  id: '/api/org/model-policy',
  path: '/api/org/model-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRouteRoute = ApiFilesUploadRouteRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesMarkdownRouteRoute = ApiFilesMarkdownRouteRouteImport.update({
  id: '/api/files/markdown',
  path: '/api/files/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const eeSingularityLayoutRouteRoute =
  eeSingularityLayoutRouteRouteImport.update({
    id: '/(ee)/singularity/_layout',
    path: '/singularity',
    getParentRoute: () => rootRouteImport,
  } as any)
const appLayoutSettingsRouteRoute = appLayoutSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutOrganizationRouteRoute =
  appLayoutOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)
const appLayoutChatRouteRoute = appLayoutChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const eeSingularityLayoutIndexRoute =
  eeSingularityLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => eeSingularityLayoutRouteRoute,
  } as any)
const appLayoutSettingsIndexRoute = appLayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutSettingsRouteRoute,
} as any)
const appLayoutChatIndexRoute = appLayoutChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutChatRouteRoute,
} as any)
const appLayoutSettingsSecurityRouteRoute =
  appLayoutSettingsSecurityRouteRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => appLayoutSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsRouteRoute =
  appLayoutOrganizationSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appLayoutOrganizationRouteRoute,
  } as any)
const appLayoutChatThreadIdRouteRoute =
  appLayoutChatThreadIdRouteRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => appLayoutChatRouteRoute,
  } as any)
const appLayoutOrganizationSettingsIndexRoute =
  appLayoutOrganizationSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const eeSingularityLayoutOrgsOrganizationIdRoute =
  eeSingularityLayoutOrgsOrganizationIdRouteImport.update({
    id: '/orgs/$organizationId',
    path: '/orgs/$organizationId',
    getParentRoute: () => eeSingularityLayoutRouteRoute,
  } as any)
const appLayoutOrganizationSettingsToolsRouteRoute =
  appLayoutOrganizationSettingsToolsRouteRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsSecurityRouteRoute =
  appLayoutOrganizationSettingsSecurityRouteRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsProviderPolicyRouteRoute =
  appLayoutOrganizationSettingsProviderPolicyRouteRouteImport.update({
    id: '/provider-policy',
    path: '/provider-policy',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsRouteRoute =
  appLayoutOrganizationSettingsModelsRouteRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsMembersRouteRoute =
  appLayoutOrganizationSettingsMembersRouteRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsKnowledgeRouteRoute =
  appLayoutOrganizationSettingsKnowledgeRouteRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsCompliancePolicyRouteRoute =
  appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport.update({
    id: '/compliance-policy',
    path: '/compliance-policy',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsByokRouteRoute =
  appLayoutOrganizationSettingsByokRouteRouteImport.update({
    id: '/byok',
    path: '/byok',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsBillingRouteRoute =
  appLayoutOrganizationSettingsBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsAnalyticsRouteRoute =
  appLayoutOrganizationSettingsAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsIndexRoute =
  appLayoutOrganizationSettingsModelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutOrganizationSettingsModelsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsProviderIdRouteRoute =
  appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => appLayoutOrganizationSettingsModelsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/pricing': typeof PricingRouteRoute
  '/setup': typeof SetupRouteRoute
  '/api/chat': typeof ApiChatRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
  '/chat': typeof appLayoutChatRouteRouteWithChildren
  '/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/settings': typeof appLayoutSettingsRouteRouteWithChildren
  '/singularity': typeof eeSingularityLayoutRouteRouteWithChildren
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appLayoutIndexRoute
  '/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/organization/settings': typeof appLayoutOrganizationSettingsRouteRouteWithChildren
  '/settings/security': typeof appLayoutSettingsSecurityRouteRoute
  '/chat/': typeof appLayoutChatIndexRoute
  '/settings/': typeof appLayoutSettingsIndexRoute
  '/singularity/': typeof eeSingularityLayoutIndexRoute
  '/organization/settings/analytics': typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  '/organization/settings/billing': typeof appLayoutOrganizationSettingsBillingRouteRoute
  '/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/organization/settings/knowledge': typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  '/organization/settings/members': typeof appLayoutOrganizationSettingsMembersRouteRoute
  '/organization/settings/models': typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  '/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/organization/settings/security': typeof appLayoutOrganizationSettingsSecurityRouteRoute
  '/organization/settings/tools': typeof appLayoutOrganizationSettingsToolsRouteRoute
  '/singularity/orgs/$organizationId': typeof eeSingularityLayoutOrgsOrganizationIdRoute
  '/organization/settings/': typeof appLayoutOrganizationSettingsIndexRoute
  '/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/organization/settings/models/': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/pricing': typeof PricingRouteRoute
  '/setup': typeof SetupRouteRoute
  '/api/chat': typeof ApiChatRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
  '/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appLayoutIndexRoute
  '/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/settings/security': typeof appLayoutSettingsSecurityRouteRoute
  '/chat': typeof appLayoutChatIndexRoute
  '/settings': typeof appLayoutSettingsIndexRoute
  '/singularity': typeof eeSingularityLayoutIndexRoute
  '/organization/settings/analytics': typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  '/organization/settings/billing': typeof appLayoutOrganizationSettingsBillingRouteRoute
  '/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/organization/settings/knowledge': typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  '/organization/settings/members': typeof appLayoutOrganizationSettingsMembersRouteRoute
  '/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/organization/settings/security': typeof appLayoutOrganizationSettingsSecurityRouteRoute
  '/organization/settings/tools': typeof appLayoutOrganizationSettingsToolsRouteRoute
  '/singularity/orgs/$organizationId': typeof eeSingularityLayoutOrgsOrganizationIdRoute
  '/organization/settings': typeof appLayoutOrganizationSettingsIndexRoute
  '/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/organization/settings/models': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/pricing': typeof PricingRouteRoute
  '/setup': typeof SetupRouteRoute
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
  '/(app)/_layout/chat': typeof appLayoutChatRouteRouteWithChildren
  '/(app)/_layout/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/(app)/_layout/settings': typeof appLayoutSettingsRouteRouteWithChildren
  '/(ee)/singularity/_layout': typeof eeSingularityLayoutRouteRouteWithChildren
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRouteRoute
  '/(app)/_layout/$': typeof appLayoutSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
  '/(app)/_layout/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/(app)/_layout/organization/settings': typeof appLayoutOrganizationSettingsRouteRouteWithChildren
  '/(app)/_layout/settings/security': typeof appLayoutSettingsSecurityRouteRoute
  '/(app)/_layout/chat/': typeof appLayoutChatIndexRoute
  '/(app)/_layout/settings/': typeof appLayoutSettingsIndexRoute
  '/(ee)/singularity/_layout/': typeof eeSingularityLayoutIndexRoute
  '/(app)/_layout/organization/settings/analytics': typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  '/(app)/_layout/organization/settings/billing': typeof appLayoutOrganizationSettingsBillingRouteRoute
  '/(app)/_layout/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/(app)/_layout/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/(app)/_layout/organization/settings/knowledge': typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  '/(app)/_layout/organization/settings/members': typeof appLayoutOrganizationSettingsMembersRouteRoute
  '/(app)/_layout/organization/settings/models': typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  '/(app)/_layout/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/(app)/_layout/organization/settings/security': typeof appLayoutOrganizationSettingsSecurityRouteRoute
  '/(app)/_layout/organization/settings/tools': typeof appLayoutOrganizationSettingsToolsRouteRoute
  '/(ee)/singularity/_layout/orgs/$organizationId': typeof eeSingularityLayoutOrgsOrganizationIdRoute
  '/(app)/_layout/organization/settings/': typeof appLayoutOrganizationSettingsIndexRoute
  '/(app)/_layout/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/(app)/_layout/organization/settings/models/': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/pricing'
    | '/setup'
    | '/api/chat'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/chat'
    | '/organization'
    | '/settings'
    | '/singularity'
    | '/api/files/markdown'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/auth/accept-invitation/$id'
    | '/$'
    | '/api/auth/$'
    | '/'
    | '/chat/$threadId'
    | '/organization/settings'
    | '/settings/security'
    | '/chat/'
    | '/settings/'
    | '/singularity/'
    | '/organization/settings/analytics'
    | '/organization/settings/billing'
    | '/organization/settings/byok'
    | '/organization/settings/compliance-policy'
    | '/organization/settings/knowledge'
    | '/organization/settings/members'
    | '/organization/settings/models'
    | '/organization/settings/provider-policy'
    | '/organization/settings/security'
    | '/organization/settings/tools'
    | '/singularity/orgs/$organizationId'
    | '/organization/settings/'
    | '/organization/settings/models/$providerId'
    | '/organization/settings/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/pricing'
    | '/setup'
    | '/api/chat'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/organization'
    | '/api/files/markdown'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/auth/accept-invitation/$id'
    | '/$'
    | '/api/auth/$'
    | '/'
    | '/chat/$threadId'
    | '/settings/security'
    | '/chat'
    | '/settings'
    | '/singularity'
    | '/organization/settings/analytics'
    | '/organization/settings/billing'
    | '/organization/settings/byok'
    | '/organization/settings/compliance-policy'
    | '/organization/settings/knowledge'
    | '/organization/settings/members'
    | '/organization/settings/provider-policy'
    | '/organization/settings/security'
    | '/organization/settings/tools'
    | '/singularity/orgs/$organizationId'
    | '/organization/settings'
    | '/organization/settings/models/$providerId'
    | '/organization/settings/models'
  id:
    | '__root__'
    | '/auth'
    | '/pricing'
    | '/setup'
    | '/(app)/_layout'
    | '/api/chat'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(app)/_layout/chat'
    | '/(app)/_layout/organization'
    | '/(app)/_layout/settings'
    | '/(ee)/singularity/_layout'
    | '/api/files/markdown'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/auth/accept-invitation/$id'
    | '/(app)/_layout/$'
    | '/api/auth/$'
    | '/(app)/_layout/'
    | '/(app)/_layout/chat/$threadId'
    | '/(app)/_layout/organization/settings'
    | '/(app)/_layout/settings/security'
    | '/(app)/_layout/chat/'
    | '/(app)/_layout/settings/'
    | '/(ee)/singularity/_layout/'
    | '/(app)/_layout/organization/settings/analytics'
    | '/(app)/_layout/organization/settings/billing'
    | '/(app)/_layout/organization/settings/byok'
    | '/(app)/_layout/organization/settings/compliance-policy'
    | '/(app)/_layout/organization/settings/knowledge'
    | '/(app)/_layout/organization/settings/members'
    | '/(app)/_layout/organization/settings/models'
    | '/(app)/_layout/organization/settings/provider-policy'
    | '/(app)/_layout/organization/settings/security'
    | '/(app)/_layout/organization/settings/tools'
    | '/(ee)/singularity/_layout/orgs/$organizationId'
    | '/(app)/_layout/organization/settings/'
    | '/(app)/_layout/organization/settings/models/$providerId'
    | '/(app)/_layout/organization/settings/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PricingRouteRoute: typeof PricingRouteRoute
  SetupRouteRoute: typeof SetupRouteRoute
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
  ApiChatRouteRoute: typeof ApiChatRouteRoute
  eeSingularityLayoutRouteRoute: typeof eeSingularityLayoutRouteRouteWithChildren
  ApiFilesMarkdownRouteRoute: typeof ApiFilesMarkdownRouteRoute
  ApiFilesUploadRouteRoute: typeof ApiFilesUploadRouteRoute
  ApiOrgModelPolicyRouteRoute: typeof ApiOrgModelPolicyRouteRoute
  ApiZeroMutateRouteRoute: typeof ApiZeroMutateRouteRoute
  ApiZeroQueryRouteRoute: typeof ApiZeroQueryRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/$': {
      id: '/(app)/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof appLayoutSplatRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/auth/accept-invitation/$id': {
      id: '/auth/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/auth/accept-invitation/$id'
      preLoaderRoute: typeof AuthAcceptInvitationIdRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/model-policy': {
      id: '/api/org/model-policy'
      path: '/api/org/model-policy'
      fullPath: '/api/org/model-policy'
      preLoaderRoute: typeof ApiOrgModelPolicyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/markdown': {
      id: '/api/files/markdown'
      path: '/api/files/markdown'
      fullPath: '/api/files/markdown'
      preLoaderRoute: typeof ApiFilesMarkdownRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ee)/singularity/_layout': {
      id: '/(ee)/singularity/_layout'
      path: '/singularity'
      fullPath: '/singularity'
      preLoaderRoute: typeof eeSingularityLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/settings': {
      id: '/(app)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appLayoutSettingsRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/organization': {
      id: '/(app)/_layout/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof appLayoutOrganizationRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/chat': {
      id: '/(app)/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appLayoutChatRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(ee)/singularity/_layout/': {
      id: '/(ee)/singularity/_layout/'
      path: '/'
      fullPath: '/singularity/'
      preLoaderRoute: typeof eeSingularityLayoutIndexRouteImport
      parentRoute: typeof eeSingularityLayoutRouteRoute
    }
    '/(app)/_layout/settings/': {
      id: '/(app)/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appLayoutSettingsIndexRouteImport
      parentRoute: typeof appLayoutSettingsRouteRoute
    }
    '/(app)/_layout/chat/': {
      id: '/(app)/_layout/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof appLayoutChatIndexRouteImport
      parentRoute: typeof appLayoutChatRouteRoute
    }
    '/(app)/_layout/settings/security': {
      id: '/(app)/_layout/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof appLayoutSettingsSecurityRouteRouteImport
      parentRoute: typeof appLayoutSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings': {
      id: '/(app)/_layout/organization/settings'
      path: '/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof appLayoutOrganizationSettingsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationRouteRoute
    }
    '/(app)/_layout/chat/$threadId': {
      id: '/(app)/_layout/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof appLayoutChatThreadIdRouteRouteImport
      parentRoute: typeof appLayoutChatRouteRoute
    }
    '/(app)/_layout/organization/settings/': {
      id: '/(app)/_layout/organization/settings/'
      path: '/'
      fullPath: '/organization/settings/'
      preLoaderRoute: typeof appLayoutOrganizationSettingsIndexRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(ee)/singularity/_layout/orgs/$organizationId': {
      id: '/(ee)/singularity/_layout/orgs/$organizationId'
      path: '/orgs/$organizationId'
      fullPath: '/singularity/orgs/$organizationId'
      preLoaderRoute: typeof eeSingularityLayoutOrgsOrganizationIdRouteImport
      parentRoute: typeof eeSingularityLayoutRouteRoute
    }
    '/(app)/_layout/organization/settings/tools': {
      id: '/(app)/_layout/organization/settings/tools'
      path: '/tools'
      fullPath: '/organization/settings/tools'
      preLoaderRoute: typeof appLayoutOrganizationSettingsToolsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/security': {
      id: '/(app)/_layout/organization/settings/security'
      path: '/security'
      fullPath: '/organization/settings/security'
      preLoaderRoute: typeof appLayoutOrganizationSettingsSecurityRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/provider-policy': {
      id: '/(app)/_layout/organization/settings/provider-policy'
      path: '/provider-policy'
      fullPath: '/organization/settings/provider-policy'
      preLoaderRoute: typeof appLayoutOrganizationSettingsProviderPolicyRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/models': {
      id: '/(app)/_layout/organization/settings/models'
      path: '/models'
      fullPath: '/organization/settings/models'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/members': {
      id: '/(app)/_layout/organization/settings/members'
      path: '/members'
      fullPath: '/organization/settings/members'
      preLoaderRoute: typeof appLayoutOrganizationSettingsMembersRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/knowledge': {
      id: '/(app)/_layout/organization/settings/knowledge'
      path: '/knowledge'
      fullPath: '/organization/settings/knowledge'
      preLoaderRoute: typeof appLayoutOrganizationSettingsKnowledgeRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/compliance-policy': {
      id: '/(app)/_layout/organization/settings/compliance-policy'
      path: '/compliance-policy'
      fullPath: '/organization/settings/compliance-policy'
      preLoaderRoute: typeof appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/byok': {
      id: '/(app)/_layout/organization/settings/byok'
      path: '/byok'
      fullPath: '/organization/settings/byok'
      preLoaderRoute: typeof appLayoutOrganizationSettingsByokRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/billing': {
      id: '/(app)/_layout/organization/settings/billing'
      path: '/billing'
      fullPath: '/organization/settings/billing'
      preLoaderRoute: typeof appLayoutOrganizationSettingsBillingRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/analytics': {
      id: '/(app)/_layout/organization/settings/analytics'
      path: '/analytics'
      fullPath: '/organization/settings/analytics'
      preLoaderRoute: typeof appLayoutOrganizationSettingsAnalyticsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/models/': {
      id: '/(app)/_layout/organization/settings/models/'
      path: '/'
      fullPath: '/organization/settings/models/'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsIndexRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsModelsRouteRoute
    }
    '/(app)/_layout/organization/settings/models/$providerId': {
      id: '/(app)/_layout/organization/settings/models/$providerId'
      path: '/$providerId'
      fullPath: '/organization/settings/models/$providerId'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsModelsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRouteRoute: typeof AuthSignInRouteRoute
  AuthSignUpRouteRoute: typeof AuthSignUpRouteRoute
  AuthAcceptInvitationIdRouteRoute: typeof AuthAcceptInvitationIdRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRouteRoute: AuthSignInRouteRoute,
  AuthSignUpRouteRoute: AuthSignUpRouteRoute,
  AuthAcceptInvitationIdRouteRoute: AuthAcceptInvitationIdRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface appLayoutChatRouteRouteChildren {
  appLayoutChatThreadIdRouteRoute: typeof appLayoutChatThreadIdRouteRoute
  appLayoutChatIndexRoute: typeof appLayoutChatIndexRoute
}

const appLayoutChatRouteRouteChildren: appLayoutChatRouteRouteChildren = {
  appLayoutChatThreadIdRouteRoute: appLayoutChatThreadIdRouteRoute,
  appLayoutChatIndexRoute: appLayoutChatIndexRoute,
}

const appLayoutChatRouteRouteWithChildren =
  appLayoutChatRouteRoute._addFileChildren(appLayoutChatRouteRouteChildren)

interface appLayoutOrganizationSettingsModelsRouteRouteChildren {
  appLayoutOrganizationSettingsModelsProviderIdRouteRoute: typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  appLayoutOrganizationSettingsModelsIndexRoute: typeof appLayoutOrganizationSettingsModelsIndexRoute
}

const appLayoutOrganizationSettingsModelsRouteRouteChildren: appLayoutOrganizationSettingsModelsRouteRouteChildren =
  {
    appLayoutOrganizationSettingsModelsProviderIdRouteRoute:
      appLayoutOrganizationSettingsModelsProviderIdRouteRoute,
    appLayoutOrganizationSettingsModelsIndexRoute:
      appLayoutOrganizationSettingsModelsIndexRoute,
  }

const appLayoutOrganizationSettingsModelsRouteRouteWithChildren =
  appLayoutOrganizationSettingsModelsRouteRoute._addFileChildren(
    appLayoutOrganizationSettingsModelsRouteRouteChildren,
  )

interface appLayoutOrganizationSettingsRouteRouteChildren {
  appLayoutOrganizationSettingsAnalyticsRouteRoute: typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  appLayoutOrganizationSettingsBillingRouteRoute: typeof appLayoutOrganizationSettingsBillingRouteRoute
  appLayoutOrganizationSettingsByokRouteRoute: typeof appLayoutOrganizationSettingsByokRouteRoute
  appLayoutOrganizationSettingsCompliancePolicyRouteRoute: typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  appLayoutOrganizationSettingsKnowledgeRouteRoute: typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  appLayoutOrganizationSettingsMembersRouteRoute: typeof appLayoutOrganizationSettingsMembersRouteRoute
  appLayoutOrganizationSettingsModelsRouteRoute: typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  appLayoutOrganizationSettingsProviderPolicyRouteRoute: typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  appLayoutOrganizationSettingsSecurityRouteRoute: typeof appLayoutOrganizationSettingsSecurityRouteRoute
  appLayoutOrganizationSettingsToolsRouteRoute: typeof appLayoutOrganizationSettingsToolsRouteRoute
  appLayoutOrganizationSettingsIndexRoute: typeof appLayoutOrganizationSettingsIndexRoute
}

const appLayoutOrganizationSettingsRouteRouteChildren: appLayoutOrganizationSettingsRouteRouteChildren =
  {
    appLayoutOrganizationSettingsAnalyticsRouteRoute:
      appLayoutOrganizationSettingsAnalyticsRouteRoute,
    appLayoutOrganizationSettingsBillingRouteRoute:
      appLayoutOrganizationSettingsBillingRouteRoute,
    appLayoutOrganizationSettingsByokRouteRoute:
      appLayoutOrganizationSettingsByokRouteRoute,
    appLayoutOrganizationSettingsCompliancePolicyRouteRoute:
      appLayoutOrganizationSettingsCompliancePolicyRouteRoute,
    appLayoutOrganizationSettingsKnowledgeRouteRoute:
      appLayoutOrganizationSettingsKnowledgeRouteRoute,
    appLayoutOrganizationSettingsMembersRouteRoute:
      appLayoutOrganizationSettingsMembersRouteRoute,
    appLayoutOrganizationSettingsModelsRouteRoute:
      appLayoutOrganizationSettingsModelsRouteRouteWithChildren,
    appLayoutOrganizationSettingsProviderPolicyRouteRoute:
      appLayoutOrganizationSettingsProviderPolicyRouteRoute,
    appLayoutOrganizationSettingsSecurityRouteRoute:
      appLayoutOrganizationSettingsSecurityRouteRoute,
    appLayoutOrganizationSettingsToolsRouteRoute:
      appLayoutOrganizationSettingsToolsRouteRoute,
    appLayoutOrganizationSettingsIndexRoute:
      appLayoutOrganizationSettingsIndexRoute,
  }

const appLayoutOrganizationSettingsRouteRouteWithChildren =
  appLayoutOrganizationSettingsRouteRoute._addFileChildren(
    appLayoutOrganizationSettingsRouteRouteChildren,
  )

interface appLayoutOrganizationRouteRouteChildren {
  appLayoutOrganizationSettingsRouteRoute: typeof appLayoutOrganizationSettingsRouteRouteWithChildren
}

const appLayoutOrganizationRouteRouteChildren: appLayoutOrganizationRouteRouteChildren =
  {
    appLayoutOrganizationSettingsRouteRoute:
      appLayoutOrganizationSettingsRouteRouteWithChildren,
  }

const appLayoutOrganizationRouteRouteWithChildren =
  appLayoutOrganizationRouteRoute._addFileChildren(
    appLayoutOrganizationRouteRouteChildren,
  )

interface appLayoutSettingsRouteRouteChildren {
  appLayoutSettingsSecurityRouteRoute: typeof appLayoutSettingsSecurityRouteRoute
  appLayoutSettingsIndexRoute: typeof appLayoutSettingsIndexRoute
}

const appLayoutSettingsRouteRouteChildren: appLayoutSettingsRouteRouteChildren =
  {
    appLayoutSettingsSecurityRouteRoute: appLayoutSettingsSecurityRouteRoute,
    appLayoutSettingsIndexRoute: appLayoutSettingsIndexRoute,
  }

const appLayoutSettingsRouteRouteWithChildren =
  appLayoutSettingsRouteRoute._addFileChildren(
    appLayoutSettingsRouteRouteChildren,
  )

interface appLayoutRouteRouteChildren {
  appLayoutChatRouteRoute: typeof appLayoutChatRouteRouteWithChildren
  appLayoutOrganizationRouteRoute: typeof appLayoutOrganizationRouteRouteWithChildren
  appLayoutSettingsRouteRoute: typeof appLayoutSettingsRouteRouteWithChildren
  appLayoutSplatRoute: typeof appLayoutSplatRoute
  appLayoutIndexRoute: typeof appLayoutIndexRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutChatRouteRoute: appLayoutChatRouteRouteWithChildren,
  appLayoutOrganizationRouteRoute: appLayoutOrganizationRouteRouteWithChildren,
  appLayoutSettingsRouteRoute: appLayoutSettingsRouteRouteWithChildren,
  appLayoutSplatRoute: appLayoutSplatRoute,
  appLayoutIndexRoute: appLayoutIndexRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

interface eeSingularityLayoutRouteRouteChildren {
  eeSingularityLayoutIndexRoute: typeof eeSingularityLayoutIndexRoute
  eeSingularityLayoutOrgsOrganizationIdRoute: typeof eeSingularityLayoutOrgsOrganizationIdRoute
}

const eeSingularityLayoutRouteRouteChildren: eeSingularityLayoutRouteRouteChildren =
  {
    eeSingularityLayoutIndexRoute: eeSingularityLayoutIndexRoute,
    eeSingularityLayoutOrgsOrganizationIdRoute:
      eeSingularityLayoutOrgsOrganizationIdRoute,
  }

const eeSingularityLayoutRouteRouteWithChildren =
  eeSingularityLayoutRouteRoute._addFileChildren(
    eeSingularityLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PricingRouteRoute: PricingRouteRoute,
  SetupRouteRoute: SetupRouteRoute,
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
  ApiChatRouteRoute: ApiChatRouteRoute,
  eeSingularityLayoutRouteRoute: eeSingularityLayoutRouteRouteWithChildren,
  ApiFilesMarkdownRouteRoute: ApiFilesMarkdownRouteRoute,
  ApiFilesUploadRouteRoute: ApiFilesUploadRouteRoute,
  ApiOrgModelPolicyRouteRoute: ApiOrgModelPolicyRouteRoute,
  ApiZeroMutateRouteRoute: ApiZeroMutateRouteRoute,
  ApiZeroQueryRouteRoute: ApiZeroQueryRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
