/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as PricingRouteRouteImport } from './routes/pricing/route'
import { Route as HealthRouteRouteImport } from './routes/health/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LegalTermsRouteRouteImport } from './routes/legal/terms/route'
import { Route as LegalPrivacyRouteRouteImport } from './routes/legal/privacy/route'
import { Route as LegalAcceptableUseRouteRouteImport } from './routes/legal/acceptable-use/route'
import { Route as AuthSignUpRouteRouteImport } from './routes/auth/sign-up/route'
import { Route as AuthSignInRouteRouteImport } from './routes/auth/sign-in/route'
import { Route as ApiChatRouteRouteImport } from './routes/api/chat/route'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutIndexRouteImport } from './routes/(app)/_layout/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appLayoutSplatRouteImport } from './routes/(app)/_layout/$'
import { Route as AuthAcceptInvitationIdRouteRouteImport } from './routes/auth/accept-invitation/$id/route'
import { Route as ApiZeroTokenRouteRouteImport } from './routes/api/zero/token/route'
import { Route as ApiZeroQueryRouteRouteImport } from './routes/api/zero/query/route'
import { Route as ApiZeroMutateRouteRouteImport } from './routes/api/zero/mutate/route'
import { Route as ApiOrgModelPolicyRouteRouteImport } from './routes/api/org/model-policy/route'
import { Route as ApiFilesUploadRouteRouteImport } from './routes/api/files/upload/route'
import { Route as ApiFilesObjectRouteRouteImport } from './routes/api/files/object/route'
import { Route as ApiFilesMarkdownRouteRouteImport } from './routes/api/files/markdown/route'
import { Route as appLayoutSettingsRouteRouteImport } from './routes/(app)/_layout/settings/route'
import { Route as appLayoutOrganizationRouteRouteImport } from './routes/(app)/_layout/organization/route'
import { Route as appLayoutOperatorRouteRouteImport } from './routes/(app)/_layout/operator/route'
import { Route as appLayoutChatRouteRouteImport } from './routes/(app)/_layout/chat/route'
import { Route as appLayoutSettingsIndexRouteImport } from './routes/(app)/_layout/settings/index'
import { Route as appLayoutChatIndexRouteImport } from './routes/(app)/_layout/chat/index'
import { Route as ApiOrgBishUploadsRouteRouteImport } from './routes/api/org/bish/uploads/route'
import { Route as ApiOrgBishRunHistoryRouteRouteImport } from './routes/api/org/bish/run-history/route'
import { Route as ApiOrgBishOverviewRouteRouteImport } from './routes/api/org/bish/overview/route'
import { Route as ApiOrgBishEvolutionRouteRouteImport } from './routes/api/org/bish/evolution/route'
import { Route as ApiOrgBishConnectorsRouteRouteImport } from './routes/api/org/bish/connectors/route'
import { Route as ApiOrgBishApprovalsRouteRouteImport } from './routes/api/org/bish/approvals/route'
import { Route as ApiOperatorBishOverviewRouteRouteImport } from './routes/api/operator/bish/overview/route'
import { Route as appLayoutSettingsSecurityRouteRouteImport } from './routes/(app)/_layout/settings/security/route'
import { Route as appLayoutOrganizationSettingsRouteRouteImport } from './routes/(app)/_layout/organization/settings/route'
import { Route as appLayoutChatThreadIdRouteRouteImport } from './routes/(app)/_layout/chat/$threadId/route'
import { Route as appLayoutOrganizationSettingsIndexRouteImport } from './routes/(app)/_layout/organization/settings/index'
import { Route as appLayoutOrganizationSettingsToolsRouteRouteImport } from './routes/(app)/_layout/organization/settings/tools/route'
import { Route as appLayoutOrganizationSettingsSecurityRouteRouteImport } from './routes/(app)/_layout/organization/settings/security/route'
import { Route as appLayoutOrganizationSettingsProviderPolicyRouteRouteImport } from './routes/(app)/_layout/organization/settings/provider-policy/route'
import { Route as appLayoutOrganizationSettingsModelsRouteRouteImport } from './routes/(app)/_layout/organization/settings/models/route'
import { Route as appLayoutOrganizationSettingsMembersRouteRouteImport } from './routes/(app)/_layout/organization/settings/members/route'
import { Route as appLayoutOrganizationSettingsKnowledgeRouteRouteImport } from './routes/(app)/_layout/organization/settings/knowledge/route'
import { Route as appLayoutOrganizationSettingsConnectorsRouteRouteImport } from './routes/(app)/_layout/organization/settings/connectors/route'
import { Route as appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport } from './routes/(app)/_layout/organization/settings/compliance-policy/route'
import { Route as appLayoutOrganizationSettingsByokRouteRouteImport } from './routes/(app)/_layout/organization/settings/byok/route'
import { Route as appLayoutOrganizationSettingsBillingRouteRouteImport } from './routes/(app)/_layout/organization/settings/billing/route'
import { Route as appLayoutOrganizationSettingsApprovalsRouteRouteImport } from './routes/(app)/_layout/organization/settings/approvals/route'
import { Route as appLayoutOrganizationSettingsAnalyticsRouteRouteImport } from './routes/(app)/_layout/organization/settings/analytics/route'
import { Route as appLayoutOrganizationSettingsAgentsRouteRouteImport } from './routes/(app)/_layout/organization/settings/agents/route'
import { Route as appLayoutOrganizationSettingsModelsIndexRouteImport } from './routes/(app)/_layout/organization/settings/models/index'
import { Route as ApiOrgBishConnectorsHubspotStartRouteRouteImport } from './routes/api/org/bish/connectors/hubspot/start/route'
import { Route as ApiOrgBishConnectorsHubspotCallbackRouteRouteImport } from './routes/api/org/bish/connectors/hubspot/callback/route'
import { Route as ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRouteImport } from './routes/api/org/bish/connectors/google-workspace/activate/route'
import { Route as ApiOrgBishConnectorsAsanaStartRouteRouteImport } from './routes/api/org/bish/connectors/asana/start/route'
import { Route as ApiOrgBishConnectorsAsanaCallbackRouteRouteImport } from './routes/api/org/bish/connectors/asana/callback/route'
import { Route as appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport } from './routes/(app)/_layout/organization/settings/models/$providerId/route'

const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRouteRoute = PricingRouteRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRouteRoute = HealthRouteRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRouteRoute = LegalTermsRouteRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRouteRoute = LegalPrivacyRouteRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRouteRoute = LegalAcceptableUseRouteRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRouteRoute = AuthSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRouteRoute = AuthSignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiChatRouteRoute = ApiChatRouteRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutIndexRoute = appLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutSplatRoute = appLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const AuthAcceptInvitationIdRouteRoute =
  AuthAcceptInvitationIdRouteRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const ApiZeroTokenRouteRoute = ApiZeroTokenRouteRouteImport.update({
  id: '/api/zero/token',
  path: '/api/zero/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroQueryRouteRoute = ApiZeroQueryRouteRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRouteRoute = ApiZeroMutateRouteRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgModelPolicyRouteRoute = ApiOrgModelPolicyRouteRouteImport.update({
  id: '/api/org/model-policy',
  path: '/api/org/model-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRouteRoute = ApiFilesUploadRouteRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesObjectRouteRoute = ApiFilesObjectRouteRouteImport.update({
  id: '/api/files/object',
  path: '/api/files/object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesMarkdownRouteRoute = ApiFilesMarkdownRouteRouteImport.update({
  id: '/api/files/markdown',
  path: '/api/files/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutSettingsRouteRoute = appLayoutSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutOrganizationRouteRoute =
  appLayoutOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)
const appLayoutOperatorRouteRoute = appLayoutOperatorRouteRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutChatRouteRoute = appLayoutChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutSettingsIndexRoute = appLayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutSettingsRouteRoute,
} as any)
const appLayoutChatIndexRoute = appLayoutChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutChatRouteRoute,
} as any)
const ApiOrgBishUploadsRouteRoute = ApiOrgBishUploadsRouteRouteImport.update({
  id: '/api/org/bish/uploads',
  path: '/api/org/bish/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgBishRunHistoryRouteRoute =
  ApiOrgBishRunHistoryRouteRouteImport.update({
    id: '/api/org/bish/run-history',
    path: '/api/org/bish/run-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgBishOverviewRouteRoute = ApiOrgBishOverviewRouteRouteImport.update({
  id: '/api/org/bish/overview',
  path: '/api/org/bish/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgBishEvolutionRouteRoute =
  ApiOrgBishEvolutionRouteRouteImport.update({
    id: '/api/org/bish/evolution',
    path: '/api/org/bish/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgBishConnectorsRouteRoute =
  ApiOrgBishConnectorsRouteRouteImport.update({
    id: '/api/org/bish/connectors',
    path: '/api/org/bish/connectors',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgBishApprovalsRouteRoute =
  ApiOrgBishApprovalsRouteRouteImport.update({
    id: '/api/org/bish/approvals',
    path: '/api/org/bish/approvals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOperatorBishOverviewRouteRoute =
  ApiOperatorBishOverviewRouteRouteImport.update({
    id: '/api/operator/bish/overview',
    path: '/api/operator/bish/overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const appLayoutSettingsSecurityRouteRoute =
  appLayoutSettingsSecurityRouteRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => appLayoutSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsRouteRoute =
  appLayoutOrganizationSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appLayoutOrganizationRouteRoute,
  } as any)
const appLayoutChatThreadIdRouteRoute =
  appLayoutChatThreadIdRouteRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => appLayoutChatRouteRoute,
  } as any)
const appLayoutOrganizationSettingsIndexRoute =
  appLayoutOrganizationSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsToolsRouteRoute =
  appLayoutOrganizationSettingsToolsRouteRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsSecurityRouteRoute =
  appLayoutOrganizationSettingsSecurityRouteRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsProviderPolicyRouteRoute =
  appLayoutOrganizationSettingsProviderPolicyRouteRouteImport.update({
    id: '/provider-policy',
    path: '/provider-policy',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsRouteRoute =
  appLayoutOrganizationSettingsModelsRouteRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsMembersRouteRoute =
  appLayoutOrganizationSettingsMembersRouteRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsKnowledgeRouteRoute =
  appLayoutOrganizationSettingsKnowledgeRouteRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsConnectorsRouteRoute =
  appLayoutOrganizationSettingsConnectorsRouteRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsCompliancePolicyRouteRoute =
  appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport.update({
    id: '/compliance-policy',
    path: '/compliance-policy',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsByokRouteRoute =
  appLayoutOrganizationSettingsByokRouteRouteImport.update({
    id: '/byok',
    path: '/byok',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsBillingRouteRoute =
  appLayoutOrganizationSettingsBillingRouteRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsApprovalsRouteRoute =
  appLayoutOrganizationSettingsApprovalsRouteRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsAnalyticsRouteRoute =
  appLayoutOrganizationSettingsAnalyticsRouteRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsAgentsRouteRoute =
  appLayoutOrganizationSettingsAgentsRouteRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsIndexRoute =
  appLayoutOrganizationSettingsModelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutOrganizationSettingsModelsRouteRoute,
  } as any)
const ApiOrgBishConnectorsHubspotStartRouteRoute =
  ApiOrgBishConnectorsHubspotStartRouteRouteImport.update({
    id: '/hubspot/start',
    path: '/hubspot/start',
    getParentRoute: () => ApiOrgBishConnectorsRouteRoute,
  } as any)
const ApiOrgBishConnectorsHubspotCallbackRouteRoute =
  ApiOrgBishConnectorsHubspotCallbackRouteRouteImport.update({
    id: '/hubspot/callback',
    path: '/hubspot/callback',
    getParentRoute: () => ApiOrgBishConnectorsRouteRoute,
  } as any)
const ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute =
  ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRouteImport.update({
    id: '/google-workspace/activate',
    path: '/google-workspace/activate',
    getParentRoute: () => ApiOrgBishConnectorsRouteRoute,
  } as any)
const ApiOrgBishConnectorsAsanaStartRouteRoute =
  ApiOrgBishConnectorsAsanaStartRouteRouteImport.update({
    id: '/asana/start',
    path: '/asana/start',
    getParentRoute: () => ApiOrgBishConnectorsRouteRoute,
  } as any)
const ApiOrgBishConnectorsAsanaCallbackRouteRoute =
  ApiOrgBishConnectorsAsanaCallbackRouteRouteImport.update({
    id: '/asana/callback',
    path: '/asana/callback',
    getParentRoute: () => ApiOrgBishConnectorsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsProviderIdRouteRoute =
  appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => appLayoutOrganizationSettingsModelsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRouteRoute
  '/pricing': typeof PricingRouteRoute
  '/setup': typeof SetupRouteRoute
  '/api/chat': typeof ApiChatRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRouteRoute
  '/legal/privacy': typeof LegalPrivacyRouteRoute
  '/legal/terms': typeof LegalTermsRouteRoute
  '/chat': typeof appLayoutChatRouteRouteWithChildren
  '/operator': typeof appLayoutOperatorRouteRoute
  '/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/settings': typeof appLayoutSettingsRouteRouteWithChildren
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/object': typeof ApiFilesObjectRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/api/zero/token': typeof ApiZeroTokenRouteRoute
  '/auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appLayoutIndexRoute
  '/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/organization/settings': typeof appLayoutOrganizationSettingsRouteRouteWithChildren
  '/settings/security': typeof appLayoutSettingsSecurityRouteRoute
  '/api/operator/bish/overview': typeof ApiOperatorBishOverviewRouteRoute
  '/api/org/bish/approvals': typeof ApiOrgBishApprovalsRouteRoute
  '/api/org/bish/connectors': typeof ApiOrgBishConnectorsRouteRouteWithChildren
  '/api/org/bish/evolution': typeof ApiOrgBishEvolutionRouteRoute
  '/api/org/bish/overview': typeof ApiOrgBishOverviewRouteRoute
  '/api/org/bish/run-history': typeof ApiOrgBishRunHistoryRouteRoute
  '/api/org/bish/uploads': typeof ApiOrgBishUploadsRouteRoute
  '/chat/': typeof appLayoutChatIndexRoute
  '/settings/': typeof appLayoutSettingsIndexRoute
  '/organization/settings/agents': typeof appLayoutOrganizationSettingsAgentsRouteRoute
  '/organization/settings/analytics': typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  '/organization/settings/approvals': typeof appLayoutOrganizationSettingsApprovalsRouteRoute
  '/organization/settings/billing': typeof appLayoutOrganizationSettingsBillingRouteRoute
  '/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/organization/settings/connectors': typeof appLayoutOrganizationSettingsConnectorsRouteRoute
  '/organization/settings/knowledge': typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  '/organization/settings/members': typeof appLayoutOrganizationSettingsMembersRouteRoute
  '/organization/settings/models': typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  '/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/organization/settings/security': typeof appLayoutOrganizationSettingsSecurityRouteRoute
  '/organization/settings/tools': typeof appLayoutOrganizationSettingsToolsRouteRoute
  '/organization/settings/': typeof appLayoutOrganizationSettingsIndexRoute
  '/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/api/org/bish/connectors/asana/callback': typeof ApiOrgBishConnectorsAsanaCallbackRouteRoute
  '/api/org/bish/connectors/asana/start': typeof ApiOrgBishConnectorsAsanaStartRouteRoute
  '/api/org/bish/connectors/google-workspace/activate': typeof ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute
  '/api/org/bish/connectors/hubspot/callback': typeof ApiOrgBishConnectorsHubspotCallbackRouteRoute
  '/api/org/bish/connectors/hubspot/start': typeof ApiOrgBishConnectorsHubspotStartRouteRoute
  '/organization/settings/models/': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRouteRoute
  '/pricing': typeof PricingRouteRoute
  '/setup': typeof SetupRouteRoute
  '/api/chat': typeof ApiChatRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRouteRoute
  '/legal/privacy': typeof LegalPrivacyRouteRoute
  '/legal/terms': typeof LegalTermsRouteRoute
  '/operator': typeof appLayoutOperatorRouteRoute
  '/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/object': typeof ApiFilesObjectRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/api/zero/token': typeof ApiZeroTokenRouteRoute
  '/auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof appLayoutIndexRoute
  '/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/settings/security': typeof appLayoutSettingsSecurityRouteRoute
  '/api/operator/bish/overview': typeof ApiOperatorBishOverviewRouteRoute
  '/api/org/bish/approvals': typeof ApiOrgBishApprovalsRouteRoute
  '/api/org/bish/connectors': typeof ApiOrgBishConnectorsRouteRouteWithChildren
  '/api/org/bish/evolution': typeof ApiOrgBishEvolutionRouteRoute
  '/api/org/bish/overview': typeof ApiOrgBishOverviewRouteRoute
  '/api/org/bish/run-history': typeof ApiOrgBishRunHistoryRouteRoute
  '/api/org/bish/uploads': typeof ApiOrgBishUploadsRouteRoute
  '/chat': typeof appLayoutChatIndexRoute
  '/settings': typeof appLayoutSettingsIndexRoute
  '/organization/settings/agents': typeof appLayoutOrganizationSettingsAgentsRouteRoute
  '/organization/settings/analytics': typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  '/organization/settings/approvals': typeof appLayoutOrganizationSettingsApprovalsRouteRoute
  '/organization/settings/billing': typeof appLayoutOrganizationSettingsBillingRouteRoute
  '/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/organization/settings/connectors': typeof appLayoutOrganizationSettingsConnectorsRouteRoute
  '/organization/settings/knowledge': typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  '/organization/settings/members': typeof appLayoutOrganizationSettingsMembersRouteRoute
  '/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/organization/settings/security': typeof appLayoutOrganizationSettingsSecurityRouteRoute
  '/organization/settings/tools': typeof appLayoutOrganizationSettingsToolsRouteRoute
  '/organization/settings': typeof appLayoutOrganizationSettingsIndexRoute
  '/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/api/org/bish/connectors/asana/callback': typeof ApiOrgBishConnectorsAsanaCallbackRouteRoute
  '/api/org/bish/connectors/asana/start': typeof ApiOrgBishConnectorsAsanaStartRouteRoute
  '/api/org/bish/connectors/google-workspace/activate': typeof ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute
  '/api/org/bish/connectors/hubspot/callback': typeof ApiOrgBishConnectorsHubspotCallbackRouteRoute
  '/api/org/bish/connectors/hubspot/start': typeof ApiOrgBishConnectorsHubspotStartRouteRoute
  '/organization/settings/models': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/health': typeof HealthRouteRoute
  '/pricing': typeof PricingRouteRoute
  '/setup': typeof SetupRouteRoute
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRouteRoute
  '/legal/privacy': typeof LegalPrivacyRouteRoute
  '/legal/terms': typeof LegalTermsRouteRoute
  '/(app)/_layout/chat': typeof appLayoutChatRouteRouteWithChildren
  '/(app)/_layout/operator': typeof appLayoutOperatorRouteRoute
  '/(app)/_layout/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/(app)/_layout/settings': typeof appLayoutSettingsRouteRouteWithChildren
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/object': typeof ApiFilesObjectRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/api/zero/token': typeof ApiZeroTokenRouteRoute
  '/auth/accept-invitation/$id': typeof AuthAcceptInvitationIdRouteRoute
  '/(app)/_layout/$': typeof appLayoutSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
  '/(app)/_layout/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/(app)/_layout/organization/settings': typeof appLayoutOrganizationSettingsRouteRouteWithChildren
  '/(app)/_layout/settings/security': typeof appLayoutSettingsSecurityRouteRoute
  '/api/operator/bish/overview': typeof ApiOperatorBishOverviewRouteRoute
  '/api/org/bish/approvals': typeof ApiOrgBishApprovalsRouteRoute
  '/api/org/bish/connectors': typeof ApiOrgBishConnectorsRouteRouteWithChildren
  '/api/org/bish/evolution': typeof ApiOrgBishEvolutionRouteRoute
  '/api/org/bish/overview': typeof ApiOrgBishOverviewRouteRoute
  '/api/org/bish/run-history': typeof ApiOrgBishRunHistoryRouteRoute
  '/api/org/bish/uploads': typeof ApiOrgBishUploadsRouteRoute
  '/(app)/_layout/chat/': typeof appLayoutChatIndexRoute
  '/(app)/_layout/settings/': typeof appLayoutSettingsIndexRoute
  '/(app)/_layout/organization/settings/agents': typeof appLayoutOrganizationSettingsAgentsRouteRoute
  '/(app)/_layout/organization/settings/analytics': typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  '/(app)/_layout/organization/settings/approvals': typeof appLayoutOrganizationSettingsApprovalsRouteRoute
  '/(app)/_layout/organization/settings/billing': typeof appLayoutOrganizationSettingsBillingRouteRoute
  '/(app)/_layout/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/(app)/_layout/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/(app)/_layout/organization/settings/connectors': typeof appLayoutOrganizationSettingsConnectorsRouteRoute
  '/(app)/_layout/organization/settings/knowledge': typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  '/(app)/_layout/organization/settings/members': typeof appLayoutOrganizationSettingsMembersRouteRoute
  '/(app)/_layout/organization/settings/models': typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  '/(app)/_layout/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/(app)/_layout/organization/settings/security': typeof appLayoutOrganizationSettingsSecurityRouteRoute
  '/(app)/_layout/organization/settings/tools': typeof appLayoutOrganizationSettingsToolsRouteRoute
  '/(app)/_layout/organization/settings/': typeof appLayoutOrganizationSettingsIndexRoute
  '/(app)/_layout/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/api/org/bish/connectors/asana/callback': typeof ApiOrgBishConnectorsAsanaCallbackRouteRoute
  '/api/org/bish/connectors/asana/start': typeof ApiOrgBishConnectorsAsanaStartRouteRoute
  '/api/org/bish/connectors/google-workspace/activate': typeof ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute
  '/api/org/bish/connectors/hubspot/callback': typeof ApiOrgBishConnectorsHubspotCallbackRouteRoute
  '/api/org/bish/connectors/hubspot/start': typeof ApiOrgBishConnectorsHubspotStartRouteRoute
  '/(app)/_layout/organization/settings/models/': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/health'
    | '/pricing'
    | '/setup'
    | '/api/chat'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/terms'
    | '/chat'
    | '/operator'
    | '/organization'
    | '/settings'
    | '/api/files/markdown'
    | '/api/files/object'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/api/zero/token'
    | '/auth/accept-invitation/$id'
    | '/$'
    | '/api/auth/$'
    | '/'
    | '/chat/$threadId'
    | '/organization/settings'
    | '/settings/security'
    | '/api/operator/bish/overview'
    | '/api/org/bish/approvals'
    | '/api/org/bish/connectors'
    | '/api/org/bish/evolution'
    | '/api/org/bish/overview'
    | '/api/org/bish/run-history'
    | '/api/org/bish/uploads'
    | '/chat/'
    | '/settings/'
    | '/organization/settings/agents'
    | '/organization/settings/analytics'
    | '/organization/settings/approvals'
    | '/organization/settings/billing'
    | '/organization/settings/byok'
    | '/organization/settings/compliance-policy'
    | '/organization/settings/connectors'
    | '/organization/settings/knowledge'
    | '/organization/settings/members'
    | '/organization/settings/models'
    | '/organization/settings/provider-policy'
    | '/organization/settings/security'
    | '/organization/settings/tools'
    | '/organization/settings/'
    | '/organization/settings/models/$providerId'
    | '/api/org/bish/connectors/asana/callback'
    | '/api/org/bish/connectors/asana/start'
    | '/api/org/bish/connectors/google-workspace/activate'
    | '/api/org/bish/connectors/hubspot/callback'
    | '/api/org/bish/connectors/hubspot/start'
    | '/organization/settings/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/health'
    | '/pricing'
    | '/setup'
    | '/api/chat'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/terms'
    | '/operator'
    | '/organization'
    | '/api/files/markdown'
    | '/api/files/object'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/api/zero/token'
    | '/auth/accept-invitation/$id'
    | '/$'
    | '/api/auth/$'
    | '/'
    | '/chat/$threadId'
    | '/settings/security'
    | '/api/operator/bish/overview'
    | '/api/org/bish/approvals'
    | '/api/org/bish/connectors'
    | '/api/org/bish/evolution'
    | '/api/org/bish/overview'
    | '/api/org/bish/run-history'
    | '/api/org/bish/uploads'
    | '/chat'
    | '/settings'
    | '/organization/settings/agents'
    | '/organization/settings/analytics'
    | '/organization/settings/approvals'
    | '/organization/settings/billing'
    | '/organization/settings/byok'
    | '/organization/settings/compliance-policy'
    | '/organization/settings/connectors'
    | '/organization/settings/knowledge'
    | '/organization/settings/members'
    | '/organization/settings/provider-policy'
    | '/organization/settings/security'
    | '/organization/settings/tools'
    | '/organization/settings'
    | '/organization/settings/models/$providerId'
    | '/api/org/bish/connectors/asana/callback'
    | '/api/org/bish/connectors/asana/start'
    | '/api/org/bish/connectors/google-workspace/activate'
    | '/api/org/bish/connectors/hubspot/callback'
    | '/api/org/bish/connectors/hubspot/start'
    | '/organization/settings/models'
  id:
    | '__root__'
    | '/auth'
    | '/health'
    | '/pricing'
    | '/setup'
    | '/(app)/_layout'
    | '/api/chat'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/terms'
    | '/(app)/_layout/chat'
    | '/(app)/_layout/operator'
    | '/(app)/_layout/organization'
    | '/(app)/_layout/settings'
    | '/api/files/markdown'
    | '/api/files/object'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/api/zero/token'
    | '/auth/accept-invitation/$id'
    | '/(app)/_layout/$'
    | '/api/auth/$'
    | '/(app)/_layout/'
    | '/(app)/_layout/chat/$threadId'
    | '/(app)/_layout/organization/settings'
    | '/(app)/_layout/settings/security'
    | '/api/operator/bish/overview'
    | '/api/org/bish/approvals'
    | '/api/org/bish/connectors'
    | '/api/org/bish/evolution'
    | '/api/org/bish/overview'
    | '/api/org/bish/run-history'
    | '/api/org/bish/uploads'
    | '/(app)/_layout/chat/'
    | '/(app)/_layout/settings/'
    | '/(app)/_layout/organization/settings/agents'
    | '/(app)/_layout/organization/settings/analytics'
    | '/(app)/_layout/organization/settings/approvals'
    | '/(app)/_layout/organization/settings/billing'
    | '/(app)/_layout/organization/settings/byok'
    | '/(app)/_layout/organization/settings/compliance-policy'
    | '/(app)/_layout/organization/settings/connectors'
    | '/(app)/_layout/organization/settings/knowledge'
    | '/(app)/_layout/organization/settings/members'
    | '/(app)/_layout/organization/settings/models'
    | '/(app)/_layout/organization/settings/provider-policy'
    | '/(app)/_layout/organization/settings/security'
    | '/(app)/_layout/organization/settings/tools'
    | '/(app)/_layout/organization/settings/'
    | '/(app)/_layout/organization/settings/models/$providerId'
    | '/api/org/bish/connectors/asana/callback'
    | '/api/org/bish/connectors/asana/start'
    | '/api/org/bish/connectors/google-workspace/activate'
    | '/api/org/bish/connectors/hubspot/callback'
    | '/api/org/bish/connectors/hubspot/start'
    | '/(app)/_layout/organization/settings/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HealthRouteRoute: typeof HealthRouteRoute
  PricingRouteRoute: typeof PricingRouteRoute
  SetupRouteRoute: typeof SetupRouteRoute
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
  ApiChatRouteRoute: typeof ApiChatRouteRoute
  LegalAcceptableUseRouteRoute: typeof LegalAcceptableUseRouteRoute
  LegalPrivacyRouteRoute: typeof LegalPrivacyRouteRoute
  LegalTermsRouteRoute: typeof LegalTermsRouteRoute
  ApiFilesMarkdownRouteRoute: typeof ApiFilesMarkdownRouteRoute
  ApiFilesObjectRouteRoute: typeof ApiFilesObjectRouteRoute
  ApiFilesUploadRouteRoute: typeof ApiFilesUploadRouteRoute
  ApiOrgModelPolicyRouteRoute: typeof ApiOrgModelPolicyRouteRoute
  ApiZeroMutateRouteRoute: typeof ApiZeroMutateRouteRoute
  ApiZeroQueryRouteRoute: typeof ApiZeroQueryRouteRoute
  ApiZeroTokenRouteRoute: typeof ApiZeroTokenRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOperatorBishOverviewRouteRoute: typeof ApiOperatorBishOverviewRouteRoute
  ApiOrgBishApprovalsRouteRoute: typeof ApiOrgBishApprovalsRouteRoute
  ApiOrgBishConnectorsRouteRoute: typeof ApiOrgBishConnectorsRouteRouteWithChildren
  ApiOrgBishEvolutionRouteRoute: typeof ApiOrgBishEvolutionRouteRoute
  ApiOrgBishOverviewRouteRoute: typeof ApiOrgBishOverviewRouteRoute
  ApiOrgBishRunHistoryRouteRoute: typeof ApiOrgBishRunHistoryRouteRoute
  ApiOrgBishUploadsRouteRoute: typeof ApiOrgBishUploadsRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/$': {
      id: '/(app)/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof appLayoutSplatRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/auth/accept-invitation/$id': {
      id: '/auth/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/auth/accept-invitation/$id'
      preLoaderRoute: typeof AuthAcceptInvitationIdRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/zero/token': {
      id: '/api/zero/token'
      path: '/api/zero/token'
      fullPath: '/api/zero/token'
      preLoaderRoute: typeof ApiZeroTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/model-policy': {
      id: '/api/org/model-policy'
      path: '/api/org/model-policy'
      fullPath: '/api/org/model-policy'
      preLoaderRoute: typeof ApiOrgModelPolicyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/object': {
      id: '/api/files/object'
      path: '/api/files/object'
      fullPath: '/api/files/object'
      preLoaderRoute: typeof ApiFilesObjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/markdown': {
      id: '/api/files/markdown'
      path: '/api/files/markdown'
      fullPath: '/api/files/markdown'
      preLoaderRoute: typeof ApiFilesMarkdownRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/settings': {
      id: '/(app)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appLayoutSettingsRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/organization': {
      id: '/(app)/_layout/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof appLayoutOrganizationRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/operator': {
      id: '/(app)/_layout/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof appLayoutOperatorRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/chat': {
      id: '/(app)/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appLayoutChatRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/settings/': {
      id: '/(app)/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appLayoutSettingsIndexRouteImport
      parentRoute: typeof appLayoutSettingsRouteRoute
    }
    '/(app)/_layout/chat/': {
      id: '/(app)/_layout/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof appLayoutChatIndexRouteImport
      parentRoute: typeof appLayoutChatRouteRoute
    }
    '/api/org/bish/uploads': {
      id: '/api/org/bish/uploads'
      path: '/api/org/bish/uploads'
      fullPath: '/api/org/bish/uploads'
      preLoaderRoute: typeof ApiOrgBishUploadsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/bish/run-history': {
      id: '/api/org/bish/run-history'
      path: '/api/org/bish/run-history'
      fullPath: '/api/org/bish/run-history'
      preLoaderRoute: typeof ApiOrgBishRunHistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/bish/overview': {
      id: '/api/org/bish/overview'
      path: '/api/org/bish/overview'
      fullPath: '/api/org/bish/overview'
      preLoaderRoute: typeof ApiOrgBishOverviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/bish/evolution': {
      id: '/api/org/bish/evolution'
      path: '/api/org/bish/evolution'
      fullPath: '/api/org/bish/evolution'
      preLoaderRoute: typeof ApiOrgBishEvolutionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/bish/connectors': {
      id: '/api/org/bish/connectors'
      path: '/api/org/bish/connectors'
      fullPath: '/api/org/bish/connectors'
      preLoaderRoute: typeof ApiOrgBishConnectorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/bish/approvals': {
      id: '/api/org/bish/approvals'
      path: '/api/org/bish/approvals'
      fullPath: '/api/org/bish/approvals'
      preLoaderRoute: typeof ApiOrgBishApprovalsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator/bish/overview': {
      id: '/api/operator/bish/overview'
      path: '/api/operator/bish/overview'
      fullPath: '/api/operator/bish/overview'
      preLoaderRoute: typeof ApiOperatorBishOverviewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/settings/security': {
      id: '/(app)/_layout/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof appLayoutSettingsSecurityRouteRouteImport
      parentRoute: typeof appLayoutSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings': {
      id: '/(app)/_layout/organization/settings'
      path: '/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof appLayoutOrganizationSettingsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationRouteRoute
    }
    '/(app)/_layout/chat/$threadId': {
      id: '/(app)/_layout/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof appLayoutChatThreadIdRouteRouteImport
      parentRoute: typeof appLayoutChatRouteRoute
    }
    '/(app)/_layout/organization/settings/': {
      id: '/(app)/_layout/organization/settings/'
      path: '/'
      fullPath: '/organization/settings/'
      preLoaderRoute: typeof appLayoutOrganizationSettingsIndexRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/tools': {
      id: '/(app)/_layout/organization/settings/tools'
      path: '/tools'
      fullPath: '/organization/settings/tools'
      preLoaderRoute: typeof appLayoutOrganizationSettingsToolsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/security': {
      id: '/(app)/_layout/organization/settings/security'
      path: '/security'
      fullPath: '/organization/settings/security'
      preLoaderRoute: typeof appLayoutOrganizationSettingsSecurityRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/provider-policy': {
      id: '/(app)/_layout/organization/settings/provider-policy'
      path: '/provider-policy'
      fullPath: '/organization/settings/provider-policy'
      preLoaderRoute: typeof appLayoutOrganizationSettingsProviderPolicyRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/models': {
      id: '/(app)/_layout/organization/settings/models'
      path: '/models'
      fullPath: '/organization/settings/models'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/members': {
      id: '/(app)/_layout/organization/settings/members'
      path: '/members'
      fullPath: '/organization/settings/members'
      preLoaderRoute: typeof appLayoutOrganizationSettingsMembersRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/knowledge': {
      id: '/(app)/_layout/organization/settings/knowledge'
      path: '/knowledge'
      fullPath: '/organization/settings/knowledge'
      preLoaderRoute: typeof appLayoutOrganizationSettingsKnowledgeRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/connectors': {
      id: '/(app)/_layout/organization/settings/connectors'
      path: '/connectors'
      fullPath: '/organization/settings/connectors'
      preLoaderRoute: typeof appLayoutOrganizationSettingsConnectorsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/compliance-policy': {
      id: '/(app)/_layout/organization/settings/compliance-policy'
      path: '/compliance-policy'
      fullPath: '/organization/settings/compliance-policy'
      preLoaderRoute: typeof appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/byok': {
      id: '/(app)/_layout/organization/settings/byok'
      path: '/byok'
      fullPath: '/organization/settings/byok'
      preLoaderRoute: typeof appLayoutOrganizationSettingsByokRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/billing': {
      id: '/(app)/_layout/organization/settings/billing'
      path: '/billing'
      fullPath: '/organization/settings/billing'
      preLoaderRoute: typeof appLayoutOrganizationSettingsBillingRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/approvals': {
      id: '/(app)/_layout/organization/settings/approvals'
      path: '/approvals'
      fullPath: '/organization/settings/approvals'
      preLoaderRoute: typeof appLayoutOrganizationSettingsApprovalsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/analytics': {
      id: '/(app)/_layout/organization/settings/analytics'
      path: '/analytics'
      fullPath: '/organization/settings/analytics'
      preLoaderRoute: typeof appLayoutOrganizationSettingsAnalyticsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/agents': {
      id: '/(app)/_layout/organization/settings/agents'
      path: '/agents'
      fullPath: '/organization/settings/agents'
      preLoaderRoute: typeof appLayoutOrganizationSettingsAgentsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/models/': {
      id: '/(app)/_layout/organization/settings/models/'
      path: '/'
      fullPath: '/organization/settings/models/'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsIndexRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsModelsRouteRoute
    }
    '/api/org/bish/connectors/hubspot/start': {
      id: '/api/org/bish/connectors/hubspot/start'
      path: '/hubspot/start'
      fullPath: '/api/org/bish/connectors/hubspot/start'
      preLoaderRoute: typeof ApiOrgBishConnectorsHubspotStartRouteRouteImport
      parentRoute: typeof ApiOrgBishConnectorsRouteRoute
    }
    '/api/org/bish/connectors/hubspot/callback': {
      id: '/api/org/bish/connectors/hubspot/callback'
      path: '/hubspot/callback'
      fullPath: '/api/org/bish/connectors/hubspot/callback'
      preLoaderRoute: typeof ApiOrgBishConnectorsHubspotCallbackRouteRouteImport
      parentRoute: typeof ApiOrgBishConnectorsRouteRoute
    }
    '/api/org/bish/connectors/google-workspace/activate': {
      id: '/api/org/bish/connectors/google-workspace/activate'
      path: '/google-workspace/activate'
      fullPath: '/api/org/bish/connectors/google-workspace/activate'
      preLoaderRoute: typeof ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRouteImport
      parentRoute: typeof ApiOrgBishConnectorsRouteRoute
    }
    '/api/org/bish/connectors/asana/start': {
      id: '/api/org/bish/connectors/asana/start'
      path: '/asana/start'
      fullPath: '/api/org/bish/connectors/asana/start'
      preLoaderRoute: typeof ApiOrgBishConnectorsAsanaStartRouteRouteImport
      parentRoute: typeof ApiOrgBishConnectorsRouteRoute
    }
    '/api/org/bish/connectors/asana/callback': {
      id: '/api/org/bish/connectors/asana/callback'
      path: '/asana/callback'
      fullPath: '/api/org/bish/connectors/asana/callback'
      preLoaderRoute: typeof ApiOrgBishConnectorsAsanaCallbackRouteRouteImport
      parentRoute: typeof ApiOrgBishConnectorsRouteRoute
    }
    '/(app)/_layout/organization/settings/models/$providerId': {
      id: '/(app)/_layout/organization/settings/models/$providerId'
      path: '/$providerId'
      fullPath: '/organization/settings/models/$providerId'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsModelsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRouteRoute: typeof AuthSignInRouteRoute
  AuthSignUpRouteRoute: typeof AuthSignUpRouteRoute
  AuthAcceptInvitationIdRouteRoute: typeof AuthAcceptInvitationIdRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRouteRoute: AuthSignInRouteRoute,
  AuthSignUpRouteRoute: AuthSignUpRouteRoute,
  AuthAcceptInvitationIdRouteRoute: AuthAcceptInvitationIdRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface appLayoutChatRouteRouteChildren {
  appLayoutChatThreadIdRouteRoute: typeof appLayoutChatThreadIdRouteRoute
  appLayoutChatIndexRoute: typeof appLayoutChatIndexRoute
}

const appLayoutChatRouteRouteChildren: appLayoutChatRouteRouteChildren = {
  appLayoutChatThreadIdRouteRoute: appLayoutChatThreadIdRouteRoute,
  appLayoutChatIndexRoute: appLayoutChatIndexRoute,
}

const appLayoutChatRouteRouteWithChildren =
  appLayoutChatRouteRoute._addFileChildren(appLayoutChatRouteRouteChildren)

interface appLayoutOrganizationSettingsModelsRouteRouteChildren {
  appLayoutOrganizationSettingsModelsProviderIdRouteRoute: typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  appLayoutOrganizationSettingsModelsIndexRoute: typeof appLayoutOrganizationSettingsModelsIndexRoute
}

const appLayoutOrganizationSettingsModelsRouteRouteChildren: appLayoutOrganizationSettingsModelsRouteRouteChildren =
  {
    appLayoutOrganizationSettingsModelsProviderIdRouteRoute:
      appLayoutOrganizationSettingsModelsProviderIdRouteRoute,
    appLayoutOrganizationSettingsModelsIndexRoute:
      appLayoutOrganizationSettingsModelsIndexRoute,
  }

const appLayoutOrganizationSettingsModelsRouteRouteWithChildren =
  appLayoutOrganizationSettingsModelsRouteRoute._addFileChildren(
    appLayoutOrganizationSettingsModelsRouteRouteChildren,
  )

interface appLayoutOrganizationSettingsRouteRouteChildren {
  appLayoutOrganizationSettingsAgentsRouteRoute: typeof appLayoutOrganizationSettingsAgentsRouteRoute
  appLayoutOrganizationSettingsAnalyticsRouteRoute: typeof appLayoutOrganizationSettingsAnalyticsRouteRoute
  appLayoutOrganizationSettingsApprovalsRouteRoute: typeof appLayoutOrganizationSettingsApprovalsRouteRoute
  appLayoutOrganizationSettingsBillingRouteRoute: typeof appLayoutOrganizationSettingsBillingRouteRoute
  appLayoutOrganizationSettingsByokRouteRoute: typeof appLayoutOrganizationSettingsByokRouteRoute
  appLayoutOrganizationSettingsCompliancePolicyRouteRoute: typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  appLayoutOrganizationSettingsConnectorsRouteRoute: typeof appLayoutOrganizationSettingsConnectorsRouteRoute
  appLayoutOrganizationSettingsKnowledgeRouteRoute: typeof appLayoutOrganizationSettingsKnowledgeRouteRoute
  appLayoutOrganizationSettingsMembersRouteRoute: typeof appLayoutOrganizationSettingsMembersRouteRoute
  appLayoutOrganizationSettingsModelsRouteRoute: typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  appLayoutOrganizationSettingsProviderPolicyRouteRoute: typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  appLayoutOrganizationSettingsSecurityRouteRoute: typeof appLayoutOrganizationSettingsSecurityRouteRoute
  appLayoutOrganizationSettingsToolsRouteRoute: typeof appLayoutOrganizationSettingsToolsRouteRoute
  appLayoutOrganizationSettingsIndexRoute: typeof appLayoutOrganizationSettingsIndexRoute
}

const appLayoutOrganizationSettingsRouteRouteChildren: appLayoutOrganizationSettingsRouteRouteChildren =
  {
    appLayoutOrganizationSettingsAgentsRouteRoute:
      appLayoutOrganizationSettingsAgentsRouteRoute,
    appLayoutOrganizationSettingsAnalyticsRouteRoute:
      appLayoutOrganizationSettingsAnalyticsRouteRoute,
    appLayoutOrganizationSettingsApprovalsRouteRoute:
      appLayoutOrganizationSettingsApprovalsRouteRoute,
    appLayoutOrganizationSettingsBillingRouteRoute:
      appLayoutOrganizationSettingsBillingRouteRoute,
    appLayoutOrganizationSettingsByokRouteRoute:
      appLayoutOrganizationSettingsByokRouteRoute,
    appLayoutOrganizationSettingsCompliancePolicyRouteRoute:
      appLayoutOrganizationSettingsCompliancePolicyRouteRoute,
    appLayoutOrganizationSettingsConnectorsRouteRoute:
      appLayoutOrganizationSettingsConnectorsRouteRoute,
    appLayoutOrganizationSettingsKnowledgeRouteRoute:
      appLayoutOrganizationSettingsKnowledgeRouteRoute,
    appLayoutOrganizationSettingsMembersRouteRoute:
      appLayoutOrganizationSettingsMembersRouteRoute,
    appLayoutOrganizationSettingsModelsRouteRoute:
      appLayoutOrganizationSettingsModelsRouteRouteWithChildren,
    appLayoutOrganizationSettingsProviderPolicyRouteRoute:
      appLayoutOrganizationSettingsProviderPolicyRouteRoute,
    appLayoutOrganizationSettingsSecurityRouteRoute:
      appLayoutOrganizationSettingsSecurityRouteRoute,
    appLayoutOrganizationSettingsToolsRouteRoute:
      appLayoutOrganizationSettingsToolsRouteRoute,
    appLayoutOrganizationSettingsIndexRoute:
      appLayoutOrganizationSettingsIndexRoute,
  }

const appLayoutOrganizationSettingsRouteRouteWithChildren =
  appLayoutOrganizationSettingsRouteRoute._addFileChildren(
    appLayoutOrganizationSettingsRouteRouteChildren,
  )

interface appLayoutOrganizationRouteRouteChildren {
  appLayoutOrganizationSettingsRouteRoute: typeof appLayoutOrganizationSettingsRouteRouteWithChildren
}

const appLayoutOrganizationRouteRouteChildren: appLayoutOrganizationRouteRouteChildren =
  {
    appLayoutOrganizationSettingsRouteRoute:
      appLayoutOrganizationSettingsRouteRouteWithChildren,
  }

const appLayoutOrganizationRouteRouteWithChildren =
  appLayoutOrganizationRouteRoute._addFileChildren(
    appLayoutOrganizationRouteRouteChildren,
  )

interface appLayoutSettingsRouteRouteChildren {
  appLayoutSettingsSecurityRouteRoute: typeof appLayoutSettingsSecurityRouteRoute
  appLayoutSettingsIndexRoute: typeof appLayoutSettingsIndexRoute
}

const appLayoutSettingsRouteRouteChildren: appLayoutSettingsRouteRouteChildren =
  {
    appLayoutSettingsSecurityRouteRoute: appLayoutSettingsSecurityRouteRoute,
    appLayoutSettingsIndexRoute: appLayoutSettingsIndexRoute,
  }

const appLayoutSettingsRouteRouteWithChildren =
  appLayoutSettingsRouteRoute._addFileChildren(
    appLayoutSettingsRouteRouteChildren,
  )

interface appLayoutRouteRouteChildren {
  appLayoutChatRouteRoute: typeof appLayoutChatRouteRouteWithChildren
  appLayoutOperatorRouteRoute: typeof appLayoutOperatorRouteRoute
  appLayoutOrganizationRouteRoute: typeof appLayoutOrganizationRouteRouteWithChildren
  appLayoutSettingsRouteRoute: typeof appLayoutSettingsRouteRouteWithChildren
  appLayoutSplatRoute: typeof appLayoutSplatRoute
  appLayoutIndexRoute: typeof appLayoutIndexRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutChatRouteRoute: appLayoutChatRouteRouteWithChildren,
  appLayoutOperatorRouteRoute: appLayoutOperatorRouteRoute,
  appLayoutOrganizationRouteRoute: appLayoutOrganizationRouteRouteWithChildren,
  appLayoutSettingsRouteRoute: appLayoutSettingsRouteRouteWithChildren,
  appLayoutSplatRoute: appLayoutSplatRoute,
  appLayoutIndexRoute: appLayoutIndexRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

interface ApiOrgBishConnectorsRouteRouteChildren {
  ApiOrgBishConnectorsAsanaCallbackRouteRoute: typeof ApiOrgBishConnectorsAsanaCallbackRouteRoute
  ApiOrgBishConnectorsAsanaStartRouteRoute: typeof ApiOrgBishConnectorsAsanaStartRouteRoute
  ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute: typeof ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute
  ApiOrgBishConnectorsHubspotCallbackRouteRoute: typeof ApiOrgBishConnectorsHubspotCallbackRouteRoute
  ApiOrgBishConnectorsHubspotStartRouteRoute: typeof ApiOrgBishConnectorsHubspotStartRouteRoute
}

const ApiOrgBishConnectorsRouteRouteChildren: ApiOrgBishConnectorsRouteRouteChildren =
  {
    ApiOrgBishConnectorsAsanaCallbackRouteRoute:
      ApiOrgBishConnectorsAsanaCallbackRouteRoute,
    ApiOrgBishConnectorsAsanaStartRouteRoute:
      ApiOrgBishConnectorsAsanaStartRouteRoute,
    ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute:
      ApiOrgBishConnectorsGoogleWorkspaceActivateRouteRoute,
    ApiOrgBishConnectorsHubspotCallbackRouteRoute:
      ApiOrgBishConnectorsHubspotCallbackRouteRoute,
    ApiOrgBishConnectorsHubspotStartRouteRoute:
      ApiOrgBishConnectorsHubspotStartRouteRoute,
  }

const ApiOrgBishConnectorsRouteRouteWithChildren =
  ApiOrgBishConnectorsRouteRoute._addFileChildren(
    ApiOrgBishConnectorsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HealthRouteRoute: HealthRouteRoute,
  PricingRouteRoute: PricingRouteRoute,
  SetupRouteRoute: SetupRouteRoute,
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
  ApiChatRouteRoute: ApiChatRouteRoute,
  LegalAcceptableUseRouteRoute: LegalAcceptableUseRouteRoute,
  LegalPrivacyRouteRoute: LegalPrivacyRouteRoute,
  LegalTermsRouteRoute: LegalTermsRouteRoute,
  ApiFilesMarkdownRouteRoute: ApiFilesMarkdownRouteRoute,
  ApiFilesObjectRouteRoute: ApiFilesObjectRouteRoute,
  ApiFilesUploadRouteRoute: ApiFilesUploadRouteRoute,
  ApiOrgModelPolicyRouteRoute: ApiOrgModelPolicyRouteRoute,
  ApiZeroMutateRouteRoute: ApiZeroMutateRouteRoute,
  ApiZeroQueryRouteRoute: ApiZeroQueryRouteRoute,
  ApiZeroTokenRouteRoute: ApiZeroTokenRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOperatorBishOverviewRouteRoute: ApiOperatorBishOverviewRouteRoute,
  ApiOrgBishApprovalsRouteRoute: ApiOrgBishApprovalsRouteRoute,
  ApiOrgBishConnectorsRouteRoute: ApiOrgBishConnectorsRouteRouteWithChildren,
  ApiOrgBishEvolutionRouteRoute: ApiOrgBishEvolutionRouteRoute,
  ApiOrgBishOverviewRouteRoute: ApiOrgBishOverviewRouteRoute,
  ApiOrgBishRunHistoryRouteRoute: ApiOrgBishRunHistoryRouteRoute,
  ApiOrgBishUploadsRouteRoute: ApiOrgBishUploadsRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
