/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiChatRouteRouteImport } from './routes/api/chat/route'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutIndexRouteImport } from './routes/(app)/_layout/index'
import { Route as appLayoutSplatRouteImport } from './routes/(app)/_layout/$'
import { Route as ApiZeroQueryRouteRouteImport } from './routes/api/zero/query/route'
import { Route as ApiZeroMutateRouteRouteImport } from './routes/api/zero/mutate/route'
import { Route as ApiOrgModelPolicyRouteRouteImport } from './routes/api/org/model-policy/route'
import { Route as ApiFilesUploadRouteRouteImport } from './routes/api/files/upload/route'
import { Route as ApiFilesMarkdownRouteRouteImport } from './routes/api/files/markdown/route'
import { Route as ApiAuthCallbackRouteRouteImport } from './routes/api/auth/callback/route'
import { Route as appLayoutWriterRouteRouteImport } from './routes/(app)/_layout/writer/route'
import { Route as appLayoutSettingsRouteRouteImport } from './routes/(app)/_layout/settings/route'
import { Route as appLayoutOrganizationRouteRouteImport } from './routes/(app)/_layout/organization/route'
import { Route as appLayoutInsightRouteRouteImport } from './routes/(app)/_layout/insight/route'
import { Route as appLayoutChatRouteRouteImport } from './routes/(app)/_layout/chat/route'
import { Route as appLayoutSettingsIndexRouteImport } from './routes/(app)/_layout/settings/index'
import { Route as appLayoutChatIndexRouteImport } from './routes/(app)/_layout/chat/index'
import { Route as appLayoutSettingsDebugAuthRouteRouteImport } from './routes/(app)/_layout/settings/debug-auth/route'
import { Route as appLayoutOrganizationSettingsRouteRouteImport } from './routes/(app)/_layout/organization/settings/route'
import { Route as appLayoutChatThreadIdRouteRouteImport } from './routes/(app)/_layout/chat/$threadId/route'
import { Route as appLayoutOrganizationSettingsIndexRouteImport } from './routes/(app)/_layout/organization/settings/index'
import { Route as appLayoutOrganizationSettingsProviderPolicyRouteRouteImport } from './routes/(app)/_layout/organization/settings/provider-policy/route'
import { Route as appLayoutOrganizationSettingsModelsRouteRouteImport } from './routes/(app)/_layout/organization/settings/models/route'
import { Route as appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport } from './routes/(app)/_layout/organization/settings/compliance-policy/route'
import { Route as appLayoutOrganizationSettingsByokRouteRouteImport } from './routes/(app)/_layout/organization/settings/byok/route'
import { Route as appLayoutOrganizationSettingsModelsIndexRouteImport } from './routes/(app)/_layout/organization/settings/models/index'
import { Route as appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport } from './routes/(app)/_layout/organization/settings/models/$providerId/route'

const ApiChatRouteRoute = ApiChatRouteRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutIndexRoute = appLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutSplatRoute = appLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const ApiZeroQueryRouteRoute = ApiZeroQueryRouteRouteImport.update({
  id: '/api/zero/query',
  path: '/api/zero/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroMutateRouteRoute = ApiZeroMutateRouteRouteImport.update({
  id: '/api/zero/mutate',
  path: '/api/zero/mutate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgModelPolicyRouteRoute = ApiOrgModelPolicyRouteRouteImport.update({
  id: '/api/org/model-policy',
  path: '/api/org/model-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRouteRoute = ApiFilesUploadRouteRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesMarkdownRouteRoute = ApiFilesMarkdownRouteRouteImport.update({
  id: '/api/files/markdown',
  path: '/api/files/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRouteRoute = ApiAuthCallbackRouteRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutWriterRouteRoute = appLayoutWriterRouteRouteImport.update({
  id: '/writer',
  path: '/writer',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutSettingsRouteRoute = appLayoutSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutOrganizationRouteRoute =
  appLayoutOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => appLayoutRouteRoute,
  } as any)
const appLayoutInsightRouteRoute = appLayoutInsightRouteRouteImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutChatRouteRoute = appLayoutChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutSettingsIndexRoute = appLayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutSettingsRouteRoute,
} as any)
const appLayoutChatIndexRoute = appLayoutChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutChatRouteRoute,
} as any)
const appLayoutSettingsDebugAuthRouteRoute =
  appLayoutSettingsDebugAuthRouteRouteImport.update({
    id: '/debug-auth',
    path: '/debug-auth',
    getParentRoute: () => appLayoutSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsRouteRoute =
  appLayoutOrganizationSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appLayoutOrganizationRouteRoute,
  } as any)
const appLayoutChatThreadIdRouteRoute =
  appLayoutChatThreadIdRouteRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => appLayoutChatRouteRoute,
  } as any)
const appLayoutOrganizationSettingsIndexRoute =
  appLayoutOrganizationSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsProviderPolicyRouteRoute =
  appLayoutOrganizationSettingsProviderPolicyRouteRouteImport.update({
    id: '/provider-policy',
    path: '/provider-policy',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsRouteRoute =
  appLayoutOrganizationSettingsModelsRouteRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsCompliancePolicyRouteRoute =
  appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport.update({
    id: '/compliance-policy',
    path: '/compliance-policy',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsByokRouteRoute =
  appLayoutOrganizationSettingsByokRouteRouteImport.update({
    id: '/byok',
    path: '/byok',
    getParentRoute: () => appLayoutOrganizationSettingsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsIndexRoute =
  appLayoutOrganizationSettingsModelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appLayoutOrganizationSettingsModelsRouteRoute,
  } as any)
const appLayoutOrganizationSettingsModelsProviderIdRouteRoute =
  appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => appLayoutOrganizationSettingsModelsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/chat': typeof ApiChatRouteRoute
  '/chat': typeof appLayoutChatRouteRouteWithChildren
  '/insight': typeof appLayoutInsightRouteRoute
  '/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/settings': typeof appLayoutSettingsRouteRouteWithChildren
  '/writer': typeof appLayoutWriterRouteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRouteRoute
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/': typeof appLayoutIndexRoute
  '/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/organization/settings': typeof appLayoutOrganizationSettingsRouteRouteWithChildren
  '/settings/debug-auth': typeof appLayoutSettingsDebugAuthRouteRoute
  '/chat/': typeof appLayoutChatIndexRoute
  '/settings/': typeof appLayoutSettingsIndexRoute
  '/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/organization/settings/models': typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  '/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/organization/settings/': typeof appLayoutOrganizationSettingsIndexRoute
  '/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/organization/settings/models/': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRoutesByTo {
  '/api/chat': typeof ApiChatRouteRoute
  '/insight': typeof appLayoutInsightRouteRoute
  '/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/writer': typeof appLayoutWriterRouteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRouteRoute
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/': typeof appLayoutIndexRoute
  '/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/settings/debug-auth': typeof appLayoutSettingsDebugAuthRouteRoute
  '/chat': typeof appLayoutChatIndexRoute
  '/settings': typeof appLayoutSettingsIndexRoute
  '/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/organization/settings': typeof appLayoutOrganizationSettingsIndexRoute
  '/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/organization/settings/models': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/(app)/_layout/chat': typeof appLayoutChatRouteRouteWithChildren
  '/(app)/_layout/insight': typeof appLayoutInsightRouteRoute
  '/(app)/_layout/organization': typeof appLayoutOrganizationRouteRouteWithChildren
  '/(app)/_layout/settings': typeof appLayoutSettingsRouteRouteWithChildren
  '/(app)/_layout/writer': typeof appLayoutWriterRouteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRouteRoute
  '/api/files/markdown': typeof ApiFilesMarkdownRouteRoute
  '/api/files/upload': typeof ApiFilesUploadRouteRoute
  '/api/org/model-policy': typeof ApiOrgModelPolicyRouteRoute
  '/api/zero/mutate': typeof ApiZeroMutateRouteRoute
  '/api/zero/query': typeof ApiZeroQueryRouteRoute
  '/(app)/_layout/$': typeof appLayoutSplatRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
  '/(app)/_layout/chat/$threadId': typeof appLayoutChatThreadIdRouteRoute
  '/(app)/_layout/organization/settings': typeof appLayoutOrganizationSettingsRouteRouteWithChildren
  '/(app)/_layout/settings/debug-auth': typeof appLayoutSettingsDebugAuthRouteRoute
  '/(app)/_layout/chat/': typeof appLayoutChatIndexRoute
  '/(app)/_layout/settings/': typeof appLayoutSettingsIndexRoute
  '/(app)/_layout/organization/settings/byok': typeof appLayoutOrganizationSettingsByokRouteRoute
  '/(app)/_layout/organization/settings/compliance-policy': typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  '/(app)/_layout/organization/settings/models': typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  '/(app)/_layout/organization/settings/provider-policy': typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  '/(app)/_layout/organization/settings/': typeof appLayoutOrganizationSettingsIndexRoute
  '/(app)/_layout/organization/settings/models/$providerId': typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  '/(app)/_layout/organization/settings/models/': typeof appLayoutOrganizationSettingsModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/chat'
    | '/chat'
    | '/insight'
    | '/organization'
    | '/settings'
    | '/writer'
    | '/api/auth/callback'
    | '/api/files/markdown'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/$'
    | '/'
    | '/chat/$threadId'
    | '/organization/settings'
    | '/settings/debug-auth'
    | '/chat/'
    | '/settings/'
    | '/organization/settings/byok'
    | '/organization/settings/compliance-policy'
    | '/organization/settings/models'
    | '/organization/settings/provider-policy'
    | '/organization/settings/'
    | '/organization/settings/models/$providerId'
    | '/organization/settings/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/chat'
    | '/insight'
    | '/organization'
    | '/writer'
    | '/api/auth/callback'
    | '/api/files/markdown'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/$'
    | '/'
    | '/chat/$threadId'
    | '/settings/debug-auth'
    | '/chat'
    | '/settings'
    | '/organization/settings/byok'
    | '/organization/settings/compliance-policy'
    | '/organization/settings/provider-policy'
    | '/organization/settings'
    | '/organization/settings/models/$providerId'
    | '/organization/settings/models'
  id:
    | '__root__'
    | '/(app)/_layout'
    | '/api/chat'
    | '/(app)/_layout/chat'
    | '/(app)/_layout/insight'
    | '/(app)/_layout/organization'
    | '/(app)/_layout/settings'
    | '/(app)/_layout/writer'
    | '/api/auth/callback'
    | '/api/files/markdown'
    | '/api/files/upload'
    | '/api/org/model-policy'
    | '/api/zero/mutate'
    | '/api/zero/query'
    | '/(app)/_layout/$'
    | '/(app)/_layout/'
    | '/(app)/_layout/chat/$threadId'
    | '/(app)/_layout/organization/settings'
    | '/(app)/_layout/settings/debug-auth'
    | '/(app)/_layout/chat/'
    | '/(app)/_layout/settings/'
    | '/(app)/_layout/organization/settings/byok'
    | '/(app)/_layout/organization/settings/compliance-policy'
    | '/(app)/_layout/organization/settings/models'
    | '/(app)/_layout/organization/settings/provider-policy'
    | '/(app)/_layout/organization/settings/'
    | '/(app)/_layout/organization/settings/models/$providerId'
    | '/(app)/_layout/organization/settings/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
  ApiChatRouteRoute: typeof ApiChatRouteRoute
  ApiAuthCallbackRouteRoute: typeof ApiAuthCallbackRouteRoute
  ApiFilesMarkdownRouteRoute: typeof ApiFilesMarkdownRouteRoute
  ApiFilesUploadRouteRoute: typeof ApiFilesUploadRouteRoute
  ApiOrgModelPolicyRouteRoute: typeof ApiOrgModelPolicyRouteRoute
  ApiZeroMutateRouteRoute: typeof ApiZeroMutateRouteRoute
  ApiZeroQueryRouteRoute: typeof ApiZeroQueryRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/$': {
      id: '/(app)/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof appLayoutSplatRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/api/zero/query': {
      id: '/api/zero/query'
      path: '/api/zero/query'
      fullPath: '/api/zero/query'
      preLoaderRoute: typeof ApiZeroQueryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zero/mutate': {
      id: '/api/zero/mutate'
      path: '/api/zero/mutate'
      fullPath: '/api/zero/mutate'
      preLoaderRoute: typeof ApiZeroMutateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org/model-policy': {
      id: '/api/org/model-policy'
      path: '/api/org/model-policy'
      fullPath: '/api/org/model-policy'
      preLoaderRoute: typeof ApiOrgModelPolicyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/markdown': {
      id: '/api/files/markdown'
      path: '/api/files/markdown'
      fullPath: '/api/files/markdown'
      preLoaderRoute: typeof ApiFilesMarkdownRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/writer': {
      id: '/(app)/_layout/writer'
      path: '/writer'
      fullPath: '/writer'
      preLoaderRoute: typeof appLayoutWriterRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/settings': {
      id: '/(app)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appLayoutSettingsRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/organization': {
      id: '/(app)/_layout/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof appLayoutOrganizationRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/insight': {
      id: '/(app)/_layout/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof appLayoutInsightRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/chat': {
      id: '/(app)/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appLayoutChatRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/settings/': {
      id: '/(app)/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appLayoutSettingsIndexRouteImport
      parentRoute: typeof appLayoutSettingsRouteRoute
    }
    '/(app)/_layout/chat/': {
      id: '/(app)/_layout/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof appLayoutChatIndexRouteImport
      parentRoute: typeof appLayoutChatRouteRoute
    }
    '/(app)/_layout/settings/debug-auth': {
      id: '/(app)/_layout/settings/debug-auth'
      path: '/debug-auth'
      fullPath: '/settings/debug-auth'
      preLoaderRoute: typeof appLayoutSettingsDebugAuthRouteRouteImport
      parentRoute: typeof appLayoutSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings': {
      id: '/(app)/_layout/organization/settings'
      path: '/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof appLayoutOrganizationSettingsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationRouteRoute
    }
    '/(app)/_layout/chat/$threadId': {
      id: '/(app)/_layout/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof appLayoutChatThreadIdRouteRouteImport
      parentRoute: typeof appLayoutChatRouteRoute
    }
    '/(app)/_layout/organization/settings/': {
      id: '/(app)/_layout/organization/settings/'
      path: '/'
      fullPath: '/organization/settings/'
      preLoaderRoute: typeof appLayoutOrganizationSettingsIndexRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/provider-policy': {
      id: '/(app)/_layout/organization/settings/provider-policy'
      path: '/provider-policy'
      fullPath: '/organization/settings/provider-policy'
      preLoaderRoute: typeof appLayoutOrganizationSettingsProviderPolicyRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/models': {
      id: '/(app)/_layout/organization/settings/models'
      path: '/models'
      fullPath: '/organization/settings/models'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/compliance-policy': {
      id: '/(app)/_layout/organization/settings/compliance-policy'
      path: '/compliance-policy'
      fullPath: '/organization/settings/compliance-policy'
      preLoaderRoute: typeof appLayoutOrganizationSettingsCompliancePolicyRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/byok': {
      id: '/(app)/_layout/organization/settings/byok'
      path: '/byok'
      fullPath: '/organization/settings/byok'
      preLoaderRoute: typeof appLayoutOrganizationSettingsByokRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsRouteRoute
    }
    '/(app)/_layout/organization/settings/models/': {
      id: '/(app)/_layout/organization/settings/models/'
      path: '/'
      fullPath: '/organization/settings/models/'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsIndexRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsModelsRouteRoute
    }
    '/(app)/_layout/organization/settings/models/$providerId': {
      id: '/(app)/_layout/organization/settings/models/$providerId'
      path: '/$providerId'
      fullPath: '/organization/settings/models/$providerId'
      preLoaderRoute: typeof appLayoutOrganizationSettingsModelsProviderIdRouteRouteImport
      parentRoute: typeof appLayoutOrganizationSettingsModelsRouteRoute
    }
  }
}

interface appLayoutChatRouteRouteChildren {
  appLayoutChatThreadIdRouteRoute: typeof appLayoutChatThreadIdRouteRoute
  appLayoutChatIndexRoute: typeof appLayoutChatIndexRoute
}

const appLayoutChatRouteRouteChildren: appLayoutChatRouteRouteChildren = {
  appLayoutChatThreadIdRouteRoute: appLayoutChatThreadIdRouteRoute,
  appLayoutChatIndexRoute: appLayoutChatIndexRoute,
}

const appLayoutChatRouteRouteWithChildren =
  appLayoutChatRouteRoute._addFileChildren(appLayoutChatRouteRouteChildren)

interface appLayoutOrganizationSettingsModelsRouteRouteChildren {
  appLayoutOrganizationSettingsModelsProviderIdRouteRoute: typeof appLayoutOrganizationSettingsModelsProviderIdRouteRoute
  appLayoutOrganizationSettingsModelsIndexRoute: typeof appLayoutOrganizationSettingsModelsIndexRoute
}

const appLayoutOrganizationSettingsModelsRouteRouteChildren: appLayoutOrganizationSettingsModelsRouteRouteChildren =
  {
    appLayoutOrganizationSettingsModelsProviderIdRouteRoute:
      appLayoutOrganizationSettingsModelsProviderIdRouteRoute,
    appLayoutOrganizationSettingsModelsIndexRoute:
      appLayoutOrganizationSettingsModelsIndexRoute,
  }

const appLayoutOrganizationSettingsModelsRouteRouteWithChildren =
  appLayoutOrganizationSettingsModelsRouteRoute._addFileChildren(
    appLayoutOrganizationSettingsModelsRouteRouteChildren,
  )

interface appLayoutOrganizationSettingsRouteRouteChildren {
  appLayoutOrganizationSettingsByokRouteRoute: typeof appLayoutOrganizationSettingsByokRouteRoute
  appLayoutOrganizationSettingsCompliancePolicyRouteRoute: typeof appLayoutOrganizationSettingsCompliancePolicyRouteRoute
  appLayoutOrganizationSettingsModelsRouteRoute: typeof appLayoutOrganizationSettingsModelsRouteRouteWithChildren
  appLayoutOrganizationSettingsProviderPolicyRouteRoute: typeof appLayoutOrganizationSettingsProviderPolicyRouteRoute
  appLayoutOrganizationSettingsIndexRoute: typeof appLayoutOrganizationSettingsIndexRoute
}

const appLayoutOrganizationSettingsRouteRouteChildren: appLayoutOrganizationSettingsRouteRouteChildren =
  {
    appLayoutOrganizationSettingsByokRouteRoute:
      appLayoutOrganizationSettingsByokRouteRoute,
    appLayoutOrganizationSettingsCompliancePolicyRouteRoute:
      appLayoutOrganizationSettingsCompliancePolicyRouteRoute,
    appLayoutOrganizationSettingsModelsRouteRoute:
      appLayoutOrganizationSettingsModelsRouteRouteWithChildren,
    appLayoutOrganizationSettingsProviderPolicyRouteRoute:
      appLayoutOrganizationSettingsProviderPolicyRouteRoute,
    appLayoutOrganizationSettingsIndexRoute:
      appLayoutOrganizationSettingsIndexRoute,
  }

const appLayoutOrganizationSettingsRouteRouteWithChildren =
  appLayoutOrganizationSettingsRouteRoute._addFileChildren(
    appLayoutOrganizationSettingsRouteRouteChildren,
  )

interface appLayoutOrganizationRouteRouteChildren {
  appLayoutOrganizationSettingsRouteRoute: typeof appLayoutOrganizationSettingsRouteRouteWithChildren
}

const appLayoutOrganizationRouteRouteChildren: appLayoutOrganizationRouteRouteChildren =
  {
    appLayoutOrganizationSettingsRouteRoute:
      appLayoutOrganizationSettingsRouteRouteWithChildren,
  }

const appLayoutOrganizationRouteRouteWithChildren =
  appLayoutOrganizationRouteRoute._addFileChildren(
    appLayoutOrganizationRouteRouteChildren,
  )

interface appLayoutSettingsRouteRouteChildren {
  appLayoutSettingsDebugAuthRouteRoute: typeof appLayoutSettingsDebugAuthRouteRoute
  appLayoutSettingsIndexRoute: typeof appLayoutSettingsIndexRoute
}

const appLayoutSettingsRouteRouteChildren: appLayoutSettingsRouteRouteChildren =
  {
    appLayoutSettingsDebugAuthRouteRoute: appLayoutSettingsDebugAuthRouteRoute,
    appLayoutSettingsIndexRoute: appLayoutSettingsIndexRoute,
  }

const appLayoutSettingsRouteRouteWithChildren =
  appLayoutSettingsRouteRoute._addFileChildren(
    appLayoutSettingsRouteRouteChildren,
  )

interface appLayoutRouteRouteChildren {
  appLayoutChatRouteRoute: typeof appLayoutChatRouteRouteWithChildren
  appLayoutInsightRouteRoute: typeof appLayoutInsightRouteRoute
  appLayoutOrganizationRouteRoute: typeof appLayoutOrganizationRouteRouteWithChildren
  appLayoutSettingsRouteRoute: typeof appLayoutSettingsRouteRouteWithChildren
  appLayoutWriterRouteRoute: typeof appLayoutWriterRouteRoute
  appLayoutSplatRoute: typeof appLayoutSplatRoute
  appLayoutIndexRoute: typeof appLayoutIndexRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutChatRouteRoute: appLayoutChatRouteRouteWithChildren,
  appLayoutInsightRouteRoute: appLayoutInsightRouteRoute,
  appLayoutOrganizationRouteRoute: appLayoutOrganizationRouteRouteWithChildren,
  appLayoutSettingsRouteRoute: appLayoutSettingsRouteRouteWithChildren,
  appLayoutWriterRouteRoute: appLayoutWriterRouteRoute,
  appLayoutSplatRoute: appLayoutSplatRoute,
  appLayoutIndexRoute: appLayoutIndexRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
  ApiChatRouteRoute: ApiChatRouteRoute,
  ApiAuthCallbackRouteRoute: ApiAuthCallbackRouteRoute,
  ApiFilesMarkdownRouteRoute: ApiFilesMarkdownRouteRoute,
  ApiFilesUploadRouteRoute: ApiFilesUploadRouteRoute,
  ApiOrgModelPolicyRouteRoute: ApiOrgModelPolicyRouteRoute,
  ApiZeroMutateRouteRoute: ApiZeroMutateRouteRoute,
  ApiZeroQueryRouteRoute: ApiZeroQueryRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
