import type { AiModelCatalogEntry } from '../types'

export const ANTHROPIC_MODELS: readonly AiModelCatalogEntry[] = [
  {
    id: 'anthropic/claude-3.5-haiku',
    providerId: 'anthropic',
    name: 'Claude 3.5 Haiku',
    description: 'Fast Claude model for lightweight turns.',
    contextWindow: 200000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: false,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_fetch'],
    reasoningEfforts: [],
    defaultMaxOutputTokens: 8192,
  },
  {
    id: 'anthropic/claude-3.7-sonnet',
    providerId: 'anthropic',
    name: 'Claude 3.7 Sonnet',
    description: 'Balanced Claude reasoning model.',
    contextWindow: 200000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: true,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_fetch'],
    reasoningEfforts: ['low', 'medium', 'high'],
    defaultReasoningEffort: 'medium',
    providerOptionsByReasoning: {
      low: { anthropic: { thinking: { type: 'enabled', budgetTokens: 4000 } } },
      medium: { anthropic: { thinking: { type: 'enabled', budgetTokens: 8000 } } },
      high: { anthropic: { thinking: { type: 'enabled', budgetTokens: 16000 } } },
    },
    defaultMaxOutputTokens: 12000,
  },
  {
    id: 'anthropic/claude-sonnet-4.5',
    providerId: 'anthropic',
    name: 'Claude Sonnet 4.5',
    description: 'High quality Claude model for long-form reasoning.',
    contextWindow: 200000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: true,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_fetch', 'computer_use'],
    reasoningEfforts: ['low', 'medium', 'high'],
    defaultReasoningEffort: 'medium',
    providerOptionsByReasoning: {
      low: { anthropic: { thinking: { type: 'enabled', budgetTokens: 4000 } } },
      medium: { anthropic: { thinking: { type: 'enabled', budgetTokens: 10000 } } },
      high: { anthropic: { thinking: { type: 'enabled', budgetTokens: 20000 } } },
    },
    defaultMaxOutputTokens: 12000,
  },
]
