import type { AiModelCatalogEntry } from '../types'

export const OPENAI_MODELS: readonly AiModelCatalogEntry[] = [
  {
    id: 'openai/gpt-4o-mini',
    providerId: 'openai',
    name: 'GPT-4o Mini',
    description: 'Fast, cost-efficient multimodal model for everyday chat.',
    contextWindow: 128000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: false,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_search', 'file_search'],
    reasoningEfforts: [],
    defaultProviderOptions: { openai: { store: false } },
    defaultMaxOutputTokens: 8192,
  },
  {
    id: 'openai/gpt-4.1',
    providerId: 'openai',
    name: 'GPT-4.1',
    description: 'Strong general-purpose model with reliable tool use.',
    contextWindow: 128000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: false,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_search', 'file_search'],
    reasoningEfforts: [],
    defaultProviderOptions: { openai: { store: false } },
    defaultMaxOutputTokens: 8192,
  },
  {
    id: 'openai/gpt-5',
    providerId: 'openai',
    name: 'GPT-5',
    description: 'Flagship reasoning and multimodal model.',
    contextWindow: 200000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: true,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_search', 'file_search', 'code_interpreter'],
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    defaultReasoningEffort: 'medium',
    providerOptionsByReasoning: {
      minimal: { openai: { reasoningEffort: 'minimal', store: false } },
      low: { openai: { reasoningEffort: 'low', store: false } },
      medium: { openai: { reasoningEffort: 'medium', store: false } },
      high: { openai: { reasoningEffort: 'high', store: false } },
    },
    defaultProviderOptions: { openai: { store: false } },
    defaultMaxOutputTokens: 12000,
  },
  {
    id: 'openai/gpt-5-mini',
    providerId: 'openai',
    name: 'GPT-5 Mini',
    description: 'Lower-latency GPT-5 variant for balanced workloads.',
    contextWindow: 200000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: true,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_search', 'file_search'],
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    defaultReasoningEffort: 'low',
    providerOptionsByReasoning: {
      minimal: { openai: { reasoningEffort: 'minimal', store: false } },
      low: { openai: { reasoningEffort: 'low', store: false } },
      medium: { openai: { reasoningEffort: 'medium', store: false } },
      high: { openai: { reasoningEffort: 'high', store: false } },
    },
    defaultProviderOptions: { openai: { store: false } },
    defaultMaxOutputTokens: 8192,
  },
  {
    id: 'openai/gpt-5.2',
    providerId: 'openai',
    name: 'GPT-5.2',
    description: 'Latest high-end GPT-5 release for complex tasks.',
    contextWindow: 200000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: true,
      supportsImageInput: true,
      supportsPdfInput: true,
    },
    providerToolIds: ['web_search', 'file_search', 'code_interpreter'],
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    defaultReasoningEffort: 'medium',
    providerOptionsByReasoning: {
      minimal: { openai: { reasoningEffort: 'minimal', store: false } },
      low: { openai: { reasoningEffort: 'low', store: false } },
      medium: { openai: { reasoningEffort: 'medium', store: false } },
      high: { openai: { reasoningEffort: 'high', store: false } },
    },
    defaultProviderOptions: { openai: { store: false } },
    defaultMaxOutputTokens: 12000,
  },
  {
    id: 'openai/gpt-5-codex',
    providerId: 'openai',
    name: 'GPT-5 Codex',
    description: 'Code-focused GPT-5 model.',
    contextWindow: 200000,
    collectsData: false,
    capabilities: {
      supportsTools: true,
      supportsStreaming: true,
      supportsReasoning: true,
      supportsImageInput: false,
      supportsPdfInput: false,
    },
    providerToolIds: ['code_interpreter'],
    reasoningEfforts: ['minimal', 'low', 'medium', 'high'],
    defaultReasoningEffort: 'medium',
    providerOptionsByReasoning: {
      minimal: { openai: { reasoningEffort: 'minimal', store: false } },
      low: { openai: { reasoningEffort: 'low', store: false } },
      medium: { openai: { reasoningEffort: 'medium', store: false } },
      high: { openai: { reasoningEffort: 'high', store: false } },
    },
    defaultProviderOptions: { openai: { store: false } },
    defaultMaxOutputTokens: 12000,
  },
]
